### ISSUE TITLE
add to ruby-toolbox.com

### ISSUE THREAD

**Issue by donpdonp** [janko-m/shrine#1]
I was struggling to remember the name of this gem after reading about it on hackernews. I figued it would be in the ruby toolbox but was not listed.

https://www.ruby-toolbox.com/categories/rails_file_uploads

can someone add/ask for this gem to be put in the upload category? thanks

**Comment by janko-m** [comment]
Hmm, I'm can't find a way how to add/ask for adding a new gem, do you know what's the procedure?

**Comment by janko-m** [comment]
When I try to suggest a project, I get: "Project suggestions are currently under maintenance and are disabled. They will be back with a vengeance soon!". So I guess it's currently not possible to add it to Ruby Toolbox, but I'll put it on my TODO list to periodically check if it's back on. Thanks for letting me know.
