### ISSUE TITLE
versions with data uri

### ISSUE THREAD

**Issue by Preen** [janko-m/shrine#110]
Hi
It would be nice to be able to create data-uri on different versions (sizes).

**Comment by janko-m** [comment]
I'm not sure I understood the question, but the data_uri plugin adds a `Shrine::UploadedFile#data_uri` method, which you can call on the uploaded versions:

```rb
Shrine.plugin :data_uri
```
```rb
photo.image[:original].data_uri
#=> "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAUA"
```

**Comment by Preen** [comment]
Ahh, this was becausre I did add the uri and version to the model after I have added records to it. After I cleaned the db I was able to get the versions etc. Thank you!
