### ISSUE TITLE
Feature request: raise on generate_location returning nil

### ISSUE THREAD

**Issue by hms** [janko-m/shrine#111]
Because of the difference in call sequence between shrine uploading and direct_uploads, I had a bug in my generate_location method that returned nil on promotion. Unfortunately, Shrine doesn't test for this and the nil was passed way, way down the stack and deep into the aws-sdk gem resulting in a very misleading error message.

I would suggest raising an error on nil before shrine proceeds with 10's of method calls and things blow up (because, with a nil location, it will eventually raise, just not in a way that is helpfule) is a better way to handle things.

I'll happily try to write a PR if you agree this is an idea worth pursuing

**Comment by janko-m** [comment]
@hms Yes, that would indeed be very helpful, I would happily accept a PR for that!
