### ISSUE TITLE
Upload via URL support

### ISSUE THREAD

**Issue by jung-hunsoo** [janko-m/shrine#116]
I'm new to shrine and trying now. And unfortunately there seems no support for remote URL upload which I've been familiar with. Even the dependency gem 'down' looks like working for it, remote url upload function isn't documented nor shown in the example codes.

**Comment by janko-m** [comment]
Not all plugins are documented in the README (there are too many :P), but they are all listed on shrinerb.com website. If you look there, you'll see the `remote_url` plugin which does what you want (using the Down gem).

**Comment by jung-hunsoo** [comment]
Thanks it helped me to enable remote_url easily. I suddenly found that there are plugin'ed methods with different naming conventions. For example as an 'avatar_data' attribute, plugin `:remote_url` adds 'avatar_remote_url' while plugin `:remove_attachment` adds 'remove_avatar'; prefix or suffix. Do you have any plan to unify them? It would be useful for metaprogramming and intuitive coding I think.

This gem's good even I've only used for less than a week, and try more.

**Comment by janko-m** [comment]
@jung-hunsoo I don't see this as an inconsistency; "remove" is a verb, while "remote url" is a noun, so it makes sense that they might be in a difference place in the sentence. In my ears `remove_attachment` makes more sense than `attachment_remove`, and `attachment_remote_url` makes more sense than `remote_attachment_url` or `remote_url_attachment`. Even if someone provided good arguments why Shrine should follow the same naming convention here, I don't think it's worthwhile to change it now and break backwards compatibility.
