### ISSUE TITLE
Shrine Image Compression

### ISSUE THREAD

**Issue by mastertechrv** [janko-m/shrine#119]
Is there a plugin for image compressing images as they are being uploaded?

**Comment by janko-m** [comment]
No, but it's much better to do compressing yourself in the processing step, for example:

```rb
require "zip" # from the "ruby-zip" gem

class MyUploader < Shrine
  plugin :processing
  process(:store) do |io, context|
    zip_file = Tempfile.new(["compressed", ".zip"], binmode: true)
    Zip::OutputStream.write_buffer(zip_file) do |zip|
      zip.put_next_entry(io.original_filename)
      io.open { |file| zip.write(file.read(16*1024)) until file.eof? }
    end
    zip_file
  end
end 
```

Note that, as per contribution guidelines, questions should be asked on the [Shrine google group](https://groups.google.com/forum/#!forum/ruby-shrine), GitHub issues should be used only for bug reports.
