### ISSUE TITLE
Return from API with complete path

### ISSUE THREAD

**Issue by brunowego** [janko-m/shrine#127]
I'm looking for a way to return the API images with the full path, along with the domain name, folder path (uploads/store). 

That would be very enjoyable. Any tips? :monkey_face:

**Comment by janko-m** [comment]
I'm not sure what exactly do you mean, uploaded file URLs contain both domain name and complete path. If you're using FileSystem storage, you just need to pass the `:host` option to `#url` with your desired domain name to have it retrieve the full URL (see the [docs](http://shrinerb.com/rdoc/classes/Shrine/Storage/FileSystem.html) for examples).

Note that as per contribution guidelines, questions should be asked on the Shrine google group, and GitHub issues should be used only for bug reports.

**Comment by buncis** [comment]
in development you can add this for full URL without adding :host in each #url 

`/config/initializers/shrine.rb`
```ruby
  Shrine.plugin :url_options, store: { host: "http://localhost:3000" }
```
