### ISSUE TITLE
Deleteing a document in development with production data

### ISSUE THREAD

**Issue by bennyzr** [janko-m/shrine#129]
Hi,

It seems that if I am using a copy of my production database on my development machine and I delete a document in development it will delete the production file in S3 since the file id is identical. 

Is there a way of not allowing deletions of production files in other environments?

**Comment by janko-m** [comment]
You can use the `keep_files` plugin:

```rb
plugin :keep_files, destroyed: true, replaced: true
```

Note that, as per contribution guidelines, questions should be asked on the Shrine google group, GitHub issues should be used only for bug reports.
