### ISSUE TITLE
Warning: Library not loaded: /usr/local/lib/libpng

### ISSUE THREAD

**Issue by hakunin** [janko-m/shrine#13]
Hi,
I just added generating thumbnails as readme suggests, but the result is not a hash where I can pass `thumb`, its still an upload.

```
Upload.last.attachment.class
  Upload Load (4.6ms)  SELECT  "uploads".* FROM "uploads"  ORDER BY "uploads"."id" DESC LIMIT 1
=> AttachmentUploader::UploadedFile
```

When I use `pry` to see whats happening there and run the resize method myself I get this output in console, but no exception, so its easy to overlook:
```
dyld: Library not loaded: /usr/local/lib/libpng15.15.dylibo.download, 300, 300)
  Referenced from: /usr/local/lib/libfreetype.6.dylib
  Reason: image not found
```

Although I have libpng installed using brew, not sure what the problem is, but maybe it would be nice to raise if there is an error like that?

**Comment by hakunin** [comment]
Interestingly, after updating the gem from github, the attachment is a hash :+1:

**Comment by janko-m** [comment]
Can you post me your `AttachmentUploader` source code so that I can reproduce (mainly to see the list of plugins)? There have been a lot of bug fixes on master (e.g. the `recache` plugin was broken), and I just want to make sure that I know what was the problem (and which commit fixed it).

**Comment by hakunin** [comment]
It was a fork of a master, but I force updated it with upstream.

Here is the uploader with both versions of the upload I used if that helps.

I was able to resolve the libpng issue by updating and upgrading brew. Had to do it, even though the libpng was installed.

```
require "image_processing/mini_magick"

class AttachmentUploader < Shrine
  include ImageProcessing::MiniMagick

  plugin :activerecord
  plugin :logging, logger: Rails.logger

  plugin :determine_mime_type
  plugin :store_dimensions
  plugin :direct_upload, max_size: 20*1024*1024, presign: -> (r) do
    r.params["fields"] || {}
  end
  plugin :remove_attachment
  plugin :versions, names: [:original, :thumb]

  def process(io, context)
    if context[:phase] == :store
      thumb = resize_to_limit!(io.download, 300, 300)
      binding.pry
      {original: io, thumb: thumb}
    end
  end

=begin
  def process(io, context)
    if context[:phase] == :store
      large = process_to_limit!(io.download, 1200, 1200)
      thumb = process_to_limit!(large,       300, 300)

      {
        original: io, 
        large: large,
        thumb: thumb,
      }
    end
  end
=end
end

```

**Comment by hakunin** [comment]
Hmm, why are the exceptions during the process silent?

I just noticed I had `process_to_limit` insteead of `resize_to_limit` (copied from different manual pages) and it just prints ot output without any exception.

**Comment by hakunin** [comment]
Ah, didn't have this set in my rails app.. `config.active_record.raise_in_transactional_callbacks = true`

**Comment by janko-m** [comment]
Yes, ActiveRecord has that unhappy default, which is going to be removed in version 5 (so errors in callbacks won't be silenced). ActiveRecord 4.2 prints deprecation warnings in the logs, which you might have noticed. I will add to the docs for `activerecord` plugin the recommendation of setting this option.
