### ISSUE TITLE
Arbitrary processing

### ISSUE THREAD

**Issue by activestylus** [janko-m/shrine#134]
Let's say I have a basic image editor on my site and I want to crop/rotate/edit images. Is there a way I can call on these functions and store the relevant versions, outside the create/upload action? I'm basically trying to update models with existing attachments.

**Comment by janko-m** [comment]
Yes, that's certainly possible. Even though you want to perform processing outside of cache/store actions, you can still keep this processing code inside the uploader, and just call it directly when you need to. The benefit of this approach is that all processing code is still in one place, and you get the benefit of Shrine's `logging` plugin if you're using it.

For your case, you could create a special `:edit` action, which you can then call directly:

```rb
class ImageUploader < Shrine
  plugin :processing
  process(:edit) do |io, context|
    # ...
  end
end
```
```rb
attacher = my_model.image_attacher
uploader = attacher.store
uploader.process(input_file, action: :edit, params: processing_params)
```

I don't know what you want the `input_file` and `processing_params` to be, so I didn't specify it. You could pass the `Shrine::UploadedFile` that's already attached, and then download it for processing inside the block, just like normal processing. The `action: :edit` parameter is the one that triggers that processing action. Basically, the two arguments that you pass to `Shrine#process` will be available in `io` and `context` variables.

Once `Shrine#process` returns the processed files, you could attach them alongside the current attachment in the way described in the [Reprocessing Versions](http://shrinerb.com/rdoc/files/doc/regenerating_versions_md.html) guide.

Note that as per contribution guidelines similar questions should be asked on the Shrine google group, GitHub issues should be used only for bug reports.
