### ISSUE TITLE
Context record id is nil when creating a new resource with an attachment

### ISSUE THREAD

**Issue by ezekg** [janko-m/shrine#140]
I have a custom storage set up for Vimeo and I'm passing in some record information so that I can query a few variables like video title, privacy settings, update status, etc. to store in Vimeo.

Here's a quick gist of what I'm doing and where my issue lies,

```ruby
class Shrine
  module Storage
    class Vimeo
      # …

      def upload(io, id, shrine_metadata: {}, **upload_options)
        # This line always fails on record_type#create because record_id is nil
        resource = shrine_metadata["record_type"].constantize
                     .find shrine_metadata["record_id"]
        
        # …
      end

      # …
    end
  end
end
```

```ruby
require "shrine"
require "shrine/storage/file_system"
require_dependency "lib/shrine/storage/vimeo"

Shrine.storages = {
  store: Shrine::Storage::FileSystem.new("public", prefix: "uploads/store"),
  vimeo: Shrine::Storage::Vimeo.new(access_token: ENV['VIMEO_ACCESS_TOKEN'])
}

Shrine.plugin :activerecord
Shrine.plugin :cached_attachment_data
Shrine.plugin :backgrounding
Shrine::Attacher.promote { |data| PromoteAttachmentWorker.perform_async data }
Shrine::Attacher.delete { |data| DeleteAttachmentWorker.perform_async data }
```

```ruby
class VideoUploader < Shrine
  plugin :default_storage, store: :vimeo
  plugin :add_metadata

  add_metadata do |io, context|
    { record_id: context[:record].id, record_type: context[:record].class.name }
  end
end
```

```ruby
class Record < ApplicationRecord
  include VideoUploader[:video]
end
```

Whenever the attachment's meta is stored, the record's ID is actually `nil` (I'm assuming it hasn't been persisted to the database yet). What do I need to do in order to get the correct context within my custom storage class? Is there a better way to get the attachment's context? I couldn't find anything documented that suggests there is.

It's also worth noting that I'm running the uploader in the background using Sidekiq + Shrine's backgrounding plugin. And [I know sometimes Sidekiq is a bit too fast](https://github.com/mperham/sidekiq/wiki/Problems-and-Troubleshooting#cannot-find-modelname-with-id12345), so this might be a race condition that needs to be solved another way.

Everything works correctly when updating an existing resource. It's only an issue whenever a new resource is created with a video attachment.

**Comment by ezekg** [comment]
This actually was a race condition. I resolved it by adding a delay to the worker,

```ruby
Shrine::Attacher.promote { |data| PromoteAttachmentWorker.perform_in 30.seconds, data }
Shrine::Attacher.delete { |data| DeleteAttachmentWorker.perform_in 30.seconds, data }
```

Might be worth noting in the docs?

**Comment by janko-m** [comment]
Yes, when extracting metadata the record will be `nil` on creation, because metadata is extracted as soon as the file is attached, which happens before the record is actually saved.

However, you shouldn't need to retrieve the record from inside the storage class, since when cached file is promoted to permanent storage the record is already retrieved. Also, the storage class should always just know about managing files (SRP 😉), and receive any upload options from the outside. You can pass options from the outside using the `upload_options` plugin:

```rb
class VideoUploader < Shrine
  plugin :upload_options, store: -> (io, context) do
    video = context[:record]
    {
      title: video.title,
      privacy: video.privacy,
      ...
    }
  end
end
```

The returned options will then be forwarded to `Shrine::Storage::Vimeo#upload`:

```rb
class Shrine
  module Storage
    class Vimeo
      # ...

      def upload(io, id, shrine_metadata: {}, **options)
        options #=> {title: "...", privacy: "...", ...}
        # ...
      end

      # ...
    end
  end
end
```

It's strange that you have to add a delay for spawning background workers (though great that you've figured it out!), because Shrine's `activerecord` plugin use the `after_commit` callback to call the block that spawns the background jobs, which means the jobs are spawned after the database transaction for creating/updating the record was committed, so the record should always be retrievable no matter how fast the worker starts processing the job 🤔

**Comment by ezekg** [comment]
I didn't know about the `upload_options` plugin, that's perfect. I didn't like the hack I put together and figured there was a better way, so thanks for pointing me in the right direction. I'm not really sure why the job processes before the record is persisted.

**Comment by janko-m** [comment]
@ezekg Happy to help 😃. Can you confirm whether you're still experiencing the race condition where you need to delay spawning the job? Were you receiving it only on creation because of the blank record ID, or did you receive it on update as well?

**Comment by ezekg** [comment]
It was just on creation, updates worked fine. Not why how Sidekiq would run before the record is persisted if Shrine is using the `after_commit` hook. I can dig in more Monday if need be.

**Comment by janko-m** [comment]
@ezekg If you're manually wrapping record creation/update around a transaction, that could be one reason (I'm pretty sure ActiveRecord doesn't nest transactions, though not 100%).

Ok, I'll close this issue for now, and if you discover that it persisted, feel free to open another issue with any details around the race condition that you found.
