### ISSUE TITLE
Using client-side direct uploader for rails model component

### ISSUE THREAD

**Issue by cmcguff** [janko-m/shrine#141]
Hi, awesome tool looking at using jquery-fileupload-rails to update a user profile picture on a user record.

Basically, User record has an Avatar_data field, single image only.

All the examples i'm looking at are for multiple file/image uploads as a child record of an existing model i.e. 1:n relationship, how do I achieve this in the above case? I got so far then got stuck thinking about it...

Example:

Editing a User record and using client-side fileupload, how do I attach this to the User model given I have not saved it yet?

**Comment by janko-m** [comment]
@cmcguff Yeah, the documentation and the demo app are definitely not explicit enough for this most common use case, sorry 😞 

The idea is that when you directly upload the file, you assign the [data hash](http://shrinerb.com/rdoc/files/doc/direct_s3_md.html#label-File+hash) to the hidden attachment field (which has the same name as the file field). If you're uploading to your app, the Shrine endpoint will automatically return the complete data hash, and just just need to write it to the app. On the other hand, if you're uploading to S3, you need to construct the data hash in JavaScript (you can see how that's done in the demo app).

If anything else is unclear, feel free to ask on the Shrine Google group.
