### ISSUE TITLE
A note about `prefix` for carrierwave migration guide

### ISSUE THREAD

**Issue by sekrett** [janko-m/shrine#142]
I was migrating from carrierwave but with local storage, not s3. The convertor is great but I realized I need to configure storage this way:
```
store: Shrine::Storage::FileSystem.new('public', prefix: '/')
````
otherwise the generated url do not work correctly. I think it is important to write about this in the guide.

**Comment by sekrett** [comment]
Or maybe the `url` should append automatically a `/` at beginning?

**Comment by janko-m** [comment]
Shrine::Storage::FileSystem currently has two "modes"; if you pass it a `:prefix` it will generate relative URLs starting with the given prefix, but if you don't it will generate full paths. That way if the files are stored on a remote FTP server, you can generate full paths to them.

```rb
Shrine::Storage::FileSystem.new("public", prefix: "uploads").url("image.jpg")
#=> "/uploads/image.jpg"
Shrine::Storage::FileSystem.new("/home/janko/uploads").url("image.jpg")
#=> "/home/janko/uploads/image.jpg"
```

However, I realized now that you can already achieve the same behaviour of generating full paths with `:prefix` as well:

```rb
Shrine::Storage::FileSystem.new("/", prefix: "/home/janko/uploads").url("image.jpg")
#=> "/home/janko/uploads/image.jpg"
```

This means that the mode without `:prefix` can in fact be removed, and we can default `:prefix` to be `/`, as you suggested. Even though use cases for that mode are very rare, it's still a breaking change so I would prefer to delay it for the next major version. For now I can just update the Shrine::Storage::FileSystem documentation to state that you have to add `prefix: "/"` if you don't have any subdirectories.

**Comment by sekrett** [comment]
Yes, I think for now it is best to update the documentation only. I don't understand what do you mean by "don't have any subdirectories" because carrierwave always has some nested directories. I wish the migration case will become not rare because Shrine is great and people should start migrating. :)
