### ISSUE TITLE
NoMethodError at /album

### ISSUE THREAD

**Issue by LutzenGrutzen** [janko-m/shrine#143]
I'm a newby to shrine and tried to learn from the demo but i got the error as mentioned, so what went wrong? Trying to set other actions in the index.erb file or fiddled around with app.rb - nothing helped. I'm using ruby 2.3.1.
Do you have any suggestions?

**Comment by janko-m** [comment]
@LutzenGrutzen Can you re-post the question on the [Shrine Google group](https://groups.google.com/forum/#!forum/ruby-shrine)? I prefer to use GitHub issues only for bug reports.

When you re-post the question there, please include the whole error including the message and backtrace (files and line numbers you get below the error), and relevant Shrine-related code including your routes.
