### ISSUE TITLE
How to do id-partitioning ?

### ISSUE THREAD

**Issue by fuminori-ido** [janko-m/shrine#144]
Hi,

PaperClip default directory structure is:

>  :rails_root/public/system/:class/:attachment/:id_partition/:style/:filename.

E.g.:

> /data/myapp/releases/20081229172410/public/system/users/avatar/000/000/013/small/my_pic.png

How can I provide such a flagmentation for my App using Shrine with local filesystem?  Or, id-partitioning is not recommended?

**Comment by janko-m** [comment]
See [one possible implementation](https://github.com/rivnefish/rivnefish/blob/2a5ebba0205dd7ce7f0bddcd4bdb5d7e272ed077/app/uploaders/id_partition.rb), you can put it in `lib/shrine/plugins/id_partition.rb`, assuming that `lib/` is in the Ruby load path. See also the discussion in https://github.com/janko-m/shrine/pull/84.

Just note that as per contribution guidelines, usage questions should be asked on the Shrine Google group, and GitHub issues should be used only for bug reports 😉

**Comment by fuminori-ido** [comment]
Thank you for pointing out the information about id-paritioning!

> usage questions should be asked on the Shrine Google group

I see, thank you!
