### ISSUE TITLE
Invalid image file

### ISSUE THREAD

**Issue by kashifnaseer** [janko-m/shrine#147]
**Invalid image file** **500** error, for ALL **Other** than IMAGE (like doc, zip etc.) uploads. 

it works fine when I upload an Image file. Ideally it should give a validation error.

A piece of code is present below to understand it better.
      
    #Models
     class Vehicle < ActiveRecord::Base
         has_one :logo, ->  class_name: Photo
         accepts_nested_attributes_for :logo, update_only: true, reject_if: :all_blank, allow_destroy: true
       end

     class Photo < ActiveRecord::Base
       include ImageUploader[:image]
     end

    #Validation class    
    class ImageUploader < Shrine
      plugin :validation_helpers

      Attacher.validate do
        validate_mime_type_inclusion [/\Aimage/], message: "is not an image"
      end

      plugin :upload_options, store: ->(io, context) do
        formatted_photoable_type = context[:record].photoable_type.include?('Vehicle') ?      context[:record].photoable_type.titleize.split(' ')[0] : context[:record].photoable_type

      {
    	   tags: [context[:record].photoable_type, "#{formatted_photoable_type}-#{context[:record].photoable_id}"]
      }
      end
    end

and following Form:
     
     #form
     = simple_form_for @vehicle, url: vehicle_path(@vehicle), html: { enctype: "multipart/form-data" } do |f|
       = f.simple_fields_for :logo do |photo_form|
            = photo_form.input :image, label: false, input_html: { type: 'hidden', value: photo_form.object.cached_image_data }
            = photo_form.input :image, label: false, input_html: { class: "custom-file-input", required: true, type: 'file'" }

Any idea, how i can get a validation message rather 500 error, when anything other than image is uploaded ?

    @vehicle = Vehicle.find(params[:id])
    @vehicle.attributes = vehicle_params // It gives 500 error at this level 
    @vehicle.save // Should it not give a validation message here ?

**Comment by janko-m** [comment]
Thanks for clarifying in https://github.com/janko-m/shrine-cloudinary/issues/1 that you're using Cloudinary, at first I wasn't sure whether this error comes from Shrine or Cloudinary. I will close this issue then and we can continue the discussion in https://github.com/janko-m/shrine-cloudinary/issues/1.
