### ISSUE TITLE
Word credentials repeated on storage/s3.rb

### ISSUE THREAD

**Issue by josueadelima** [janko-m/shrine#149]
On line 304 word credentials is repeated

s3.client.config.**credentials.credentials**.access_key_id

**Comment by janko-m** [comment]
This was done intentionally, because I saw https://github.com/refile/refile-s3/pull/31 and https://github.com/refile/refile-s3/pull/18 being raised. However, I think this not needed, as we can access the credentials directly from `Aws::S3::Client#config`. I will push a change shortly for this.

**Comment by josueadelima** [comment]
Thanks!, this was generating an error, using the aws-sdk 2.8.7 and using cache and store with S3, will download the shrine again from github repository

**Comment by janko-m** [comment]
@josueadelima Can you tell me which error it was raising? I cannot reproduce it with aws-sdk 2.8.7:

```rb
require "aws-sdk"

puts Aws::VERSION

resource = Aws::S3::Resource.new(
  access_key_id: "abc",
  secret_access_key: "xyz",
  region: "eu-west-1"
)

puts resource.client.config.credentials.credentials.access_key_id
```
```
2.8.7
abc
```

**Comment by josueadelima** [comment]
Sorry, I had an error in my gem file with the aws-sdk, and I was using an old version, I cannot reproduce the error anymore, but it was:

`NoMethodError: undefined method `credentials' for #<Aws::Credentials access_key_id`

Thats how I noticed the word was repeated
