### ISSUE TITLE
"thumbor" storage

### ISSUE THREAD

**Issue by havran** [janko-m/shrine#154]
Hi, i'm trying create new shrine storage for [Thumbor](http://thumbor.org/). I try implement basic class as described in documentation (http://shrinerb.com/rdoc/files/doc/creating_storages_md.html). 

Thumbor use REST API for posting images and constructed URLs for geting images. 

I want send image to thumbor server with RestClient. 

I have little success (because my lack of experience with advanced ruby coding). Maybe there is better way?

And one question. Why is storage upload method called twice? First time with io = ActionDispatch::Http::UploadedFile object and second time with io = MyUploaderClass::UploadedFile?

Thanks for advices.

Juraj

**Comment by havran** [comment]
I understand now - first time is called upload to cache and second time move to store.

For now i get this code - partialy working - but model.image.url return nil.

```ruby
require "shrine"
require "down"

class Shrine
  module Storage
    class Thumbor
      def initialize
        @thumbor_base_url = 'https://img.uid.is'
        @thumbor_api      = "#{@thumbor_base_url}/image"
      end

      def upload(io, id, shrine_metadata: {}, **upload_options)
        # uploads `io` to the location `id`, can accept upload options
        slug      = shrine_metadata['filename']
        mime_type = shrine_metadata['mime_type']

        response = RestClient.post(
          @thumbor_api,
          io.read,
          {
            'Content-Type' => mime_type,
            'Slug' => slug
          }
        )

        id.replace(response.headers[:location])
        shrine_metadata.merge!({location: response.headers[:location]})
      end

      def url(id, **options)
        # returns URL to the remote file, accepts options for customizing the URL
        binding.pry
        "#{@thumbor_base_url}#{id}"
      end

      def open(id)
        # returns the remote file as an IO-like object
        Down.open("#{@thumbor_base_url}#{id}")
      end

      def exists?(id)
        # checks if the file exists on the storage
      end

      def delete(id)
        # deletes the file from the storage
      end
    end
  end
end
```

**Comment by janko-m** [comment]
You definitely got the main points figured out 👍
Could you please repost this code on the Shrine Google group, so that we can talk about it further there, as I prefer to use GitHub issues only for bug reports (I definitely have a few tips to share) 😉
