### ISSUE TITLE
NoMethodError: undefined method `find_record' for Shrine::Attacher:Class

### ISSUE THREAD

**Issue by hakunin** [janko-m/shrine#16]
The background attacher seems ot be missing a method, called here:
https://github.com/janko-m/shrine/blob/47484f9d9c7833b0bed228f8c0d887b7d33757de/lib/shrine/plugins/background_helpers.rb#L80

```
require "shrine"
require "shrine/storage/file_system"
require "shrine/storage/s3"

s3_options = {
  access_key_id:     ENV['AWS_ACCESS_KEY_ID'],      # "xyz"
  secret_access_key: ENV['AWS_SECRET_ACCESS_KEY'],  # "abc"
  region:            ENV['AWS_REGION'],             # "eu-west-1"
  bucket:            ENV['AWS_BUCKET'],             # "my-app"
}

Shrine.storages = {
  cache: Shrine::Storage::S3.new(prefix: "cache", **s3_options),
  store: Shrine::Storage::S3.new(prefix: "store", **s3_options),
}

Shrine.plugin :direct_upload, presign: true, max_size: nil #20*1024*1024
Shrine.plugin :background_helpers

Shrine::Attacher.promote { |data| ShrineUploadJob.perform_async(data) }
Shrine::Attacher.delete { |data| ShrineDeleteJob.perform_async(data) }

class ShrineUploadJob
  include Sidekiq::Worker
  def perform(data)
    Shrine::Attacher.promote(data)
  end
end

class ShrineDeleteJob
  include Sidekiq::Worker
  def perform(data)
    Shrine::Attacher.delete(data)
  end
end
```

**Comment by janko-m** [comment]
You forgot to load the ORM plugin:

```rb
Shrine.plugin :activerecord
```

I commented about it on the previous issue as well (https://github.com/janko-m/shrine/issues/19#issuecomment-159291609), I don't know what's the best solution to prevent this, I'll open a thread in the Google group.

**Comment by hakunin** [comment]
Couple of ideas:
1) autodetect rails and include it - probably don't want to do that
2) use respon_to? to sniff it and provide a helpful exception

**Comment by janko-m** [comment]
I moved this discussion to the [Google group](https://groups.google.com/forum/#!topic/ruby-shrine/mVHtwVx5a4I). The second idea would only solve this caveat for the `background_helpers` plugin, but not in general.
