### ISSUE TITLE
File download with original filename

### ISSUE THREAD

**Issue by chaitalipatel** [janko-m/shrine#162]
Hi 

Thanks for this awesome gem. - Really appreciate.

How do I download the file with its original filename? currently, the file gets downloaded by its id.

**Comment by janko-m** [comment]
I'm assuming you're using filesystem storage. For now the only way to have file downloaded by filename is to actually save files to a location that ends with their filename. When the `Content-Disposition` response header is absent, the browser will default to using the last component of the URL as the filename.

```rb
class MyUploader < Shrine
  def generate_location(io, context)
    [super, *context[:metadata]["filename"]].join("/")
  end
end
```

-----

But there is feature in the `download_endpoint` plugin that has been in my backlog for some time, which would automatically apply the behaviour you're requesting. The `download_endpoint` plugin provides a Rack endpoint which is an alternative way to download files (alternative to the `Rack::File` middleware in case of filesystem storage).

```rb
mount Shrine::DownloadEndpoint => "/attachments"
```

It has the ability to set the `Content-Disposition` response header to any file (which the browser would use a the download filename), but it currently doesn't know what is the original filename, it only knows what the URL provides and that's the uploaded file id.

```rb
uploaded_file.url #=> "/attachments/<file-id>"
```

The simplest solution would probably be to modify `Shrine::UploadedFile#url`, which generates the URL to the download endpoint when the `download_endpoint` plugin is loaded, to add an additional `filename` query parameter to the URL, which the download endpoint can then use to populate the `Content-Disposition` response header.

```rb
uploaded_file.url #=> "/attachments/<file-id>?filename=nature.jpg"
```

----

However, I think there is a better solution which would be more flexible, one which would expose *all* metadata to the download endpoint. The idea is to take the whole uploaded file hash

```rb
{
  "id": "9sguo8u298u.jpg",
  "storage": "store",
  "metadata": {
    "filename": "nature.jpg",
    "mime_type": "image/jpeg",
    "size": 893825 
  }
}
```

and encode it into an URL-safe identifier, and then use it as the URL. The download endpoint would then receive that string, decode it back into a hash, and have all the file information available. That would be more flexible for several reasons:

* it would be able to set the correct `Content-Disposition` header (your use case)
* it would always set the correct `Content-Type` response header, whereas currently `Content-Type` is determine from file id extension using `Rack::Mime`, which doesn't know about all MIME types, and the file id might not have a file extension in all scenarios.
* it would account for cases where the storage itself doesn't know about the filesize of the file, so then the `size` metadata could be used for the `Content-Length` header as a fallback.
* it would allow obfuscating the file id from the user by using a secret key when encoding the hash
* it would remove `cache`/`store` from the URL, which is unnecessary information for the user

[Dragonfly](https://github.com/markevans/dragonfly/blob/master/lib/dragonfly/app.rb) does the same thing, it encodes processing commands in the URL, so this would probably use the same implementation as Dragonfly.

**Comment by janko-m** [comment]
This has been fixed in https://github.com/janko-m/shrine/commit/e333647ab5ada1ba7ec95d836130baa17fd61a8b, which makes the `download_endpoint` automatically use the `filename` metadata value in the `Content-Disposition` header. So, to fix the issue, instead of having Rails/Rack serve the uploaded files, use `download_endpoint` instead.
