### ISSUE TITLE
Use several cache storages

### ISSUE THREAD

**Issue by emmanuelmillionaer** [janko-m/shrine#164]
Hi, @janko-m  thanks for this great gem! 🙂  It's amazing 🥇 

Now I added a new Uploader `User::ImageUploader` and there I would like to use the `shrine-url` gem. That means I would like to pass in Image-Urls and let them download in the background. 

That's why I added a new storage `url`:

```

Shrine.storages = {
     cache: Shrine::Storage::PublicS3.new(prefix: "cache", upload_options: { acl: "public-read", cache_control: "public, max-age=#{30.days}" }, **s3_options),
     store: Shrine::Storage::PublicS3.new(prefix: "store", upload_options: { acl: "public-read", cache_control: "public, max-age=#{30.days}" }, **s3_options),
     url: Shrine::Storage::Url.new
}
```

And I attach user images like that:
```
data = {"storage" => "url", "id" => "https://www.urlaubsguru.de/wp-content/uploads/2017/04/barceloneta-barcelona-spain-istock_000015072983_large-768x265.jpg", "metadata" => {}}
user.image = Shrine.uploaded_file(data)
```

But as you can see from the output, it's not using the `url` cache strategy. It's using the normal cache strategy and downloads the image directly:

```
=> #<Shrine::UploadedFile:0x007f0c380a3098 @data={"storage"=>"url", "id"=>"https://www.urlaubsguru.de/wp-content/uploads/2017/04/barceloneta-barcelona-spain-istock_000015072983_large-768x265.jpg", "metadata"=>{}}, 
@io=#<Down::ChunkedIO:0x0000000a520968 @size=83229, @chunks=#<Enumerator: #<Net::HTTPOK 200 OK readbody=true>:read_body>, 
@on_close=nil, @tempfile=#<Tempfile: (closed)>>>
>>  user.image
=> #<Product::ImageUploader::UploadedFile:0x007f0c3009e000 @data={"id"=>"7dd63fb3de5baeb59fa48e59efd049f5.jpg", 
"storage"=>"cache", "metadata"=>{}}>
```

When I modify the storages, and overwrite cache to use Shrine::Storage::Url.new:

```
Shrine.storages = {
     cache: Shrine::Storage::Url.new,
     store: Shrine::Storage::PublicS3.new(prefix: "store", upload_options: { acl: "public-read", cache_control: "public, max-age=#{30.days}" }, **s3_options)
}
```

then it works correctly and downloads the images in the background. But for some uploaders I would like to use the normal cache-strategy, for others like the `User::ImageUploader` I would like to use the `shrine-url` strategy. 

How would you configure the storages? 🙂  How would you pass in the image-urls? 🙂  Thank you a lot @janko-m 👍  You created an extraordinary gem!

**Comment by emmanuelmillionaer** [comment]
I managed to attach the Image to the user by passing storage options to a attacher:

```
      attacher = User::ImageUploader::Attacher.new(user, :image, cache: :url, store: :store)
      data = {"storage" => "url",
              "id" => image_url,
              "metadata" => {}}
      attacher.set Shrine.uploaded_file(data)
      user.save
      attacher._promote
```

Is this order correct? Would you propose something else? 🙂  Thanks for your efforts

**Comment by janko-m** [comment]
You can use the `default_storage` plugin to change the temporary storage, which internally works like your solution (it just overrides `Shrine::Attacher#initialize`).

```rb
class ImageUploader < Shrine
  plugin :default_storage, cache: :url
end
```

The following code:

```rb
data = {"storage" => "url", "id" => "https://www.urlaubsguru.de/wp-content/uploads/2017/04/barceloneta-barcelona-spain-istock_000015072983_large-768x265.jpg", "metadata" => {}}
user.image = Shrine.uploaded_file(data)
```

won't work as you expected, because `Shrine::Attacher#assign` will treat `Shrine::UploadedFile` objects just as any other IO objects, and it will copy it to cache. This behaviour is deliberate, as this gives more flexibility in certain cases. You can use `Shrine::Attacher#set` to assign `Shrine::UploadedFile` objects directly.

However, the attachment setter already has a way of accepting cached files, you need to assign them in the JSON format:

```rb
data = {"storage" => "url", "id" => "https://www.urlaubsguru.de/wp-content/uploads/2017/04/barceloneta-barcelona-spain-istock_000015072983_large-768x265.jpg", "metadata" => {}}
user.image = data.to_json
```

Note that this will only work if the `Shrine::Attacher`'s temporary storage matches the `storage`, otherwise the assignment will just be discarded.

**Comment by emmanuelmillionaer** [comment]
Thank you a lot @janko-m for this advice! 🙂  Wish you a really good day! ☀️
