### ISSUE TITLE
How to overwrite url

### ISSUE THREAD

**Issue by emmanuelmillionaer** [janko-m/shrine#166]
Hi @janko-m , thanks for this amazing gem! 🙂  It's functionalities are impressive 💯 

I'm using the `remote_url` plugin and I would like to show only images if they are stored. As long as they are not stored it should return the `default_url`. 

I thought I could maybe overwrite the Attachment `url` Method with the `module_include` plugin but it seems not to work.

```
  plugin :module_include
  attachment_module do
    def url(**options)
       stored? ? super : default_url
    end
  end
```

Can you give me a hint how it could work? 🙂  Thanks for your efforts you put into this gem.

**Comment by janko-m** [comment]
You need to override `#url` on `Shrine::Attacher`, not `Shrine::Attachment`, so you need to use `attacher_module`:

```rb
  plugin :module_include
  attacher_module do
    def url(**options)
       stored? ? super : default_url
    end
  end
```

Note that usage questions should be asked on the Google Group, GitHub issues should be used only for bug reports.
