### ISSUE TITLE
Passing multiple arguments to ActiveRecord::Errors

### ISSUE THREAD

**Issue by ypresto** [janko-m/shrine#168]
Current `:activerecord` plugin only passes localized `message` arg to ActiveRecord::Errors.

```rb
          model.class_eval <<-RUBY, __FILE__, __LINE__ + 1 if opts[:activerecord_validations]
            validate do
              #{@name}_attacher.errors.each do |message|
                errors.add(:#{@name}, message)
              end
            end
          RUBY
```

But in rails-way it'd be better that I18n is done in ActiveRecord::Errors itself.
So I want to return multiple args for `message:` of validation:

```rb
validate_max_size 256 * 1024**2, message: ->(max) { [:max_size, max: max] }
```
Or below is more verbose way:

```rb
validate_max_size 256 * 1024**2, on_error: ->(record, max) { record.errors.add(:max_size, max: max) }
```

What do you think about this idea?
Thanks!

**Comment by ypresto** [comment]
Currently I'm using something like this:

```rb
validate_max_size 256 * 1024**2, message: ->(max) { record.errors.generate_message(name, :max_size, max: max) }
```

**Comment by janko-m** [comment]
@ypresto Thanks for the detailed description. I agree, I think Shrine should support

```
validate_max_size 256 * 1024**2, message: ->(max) { [:max_size, max: max] }
```

This is really easy to support, the message can just be splatted when passed to `record.errors.add`, and then if it's an array it will be passed as multiple arguments. I will push a fix for it shortly.
