### ISSUE TITLE
Returning S3 Urls as Json Hash

### ISSUE THREAD

**Issue by uurcankaya** [janko-m/shrine#170]
Hi,

Is there an easy way to return s3 urls as json hash in this gem? 

image data does not contain any urls, such call does not help

`@photos = @photos.all.as_json(only: [:image_data])`

are there any helpers exists to calculate s3 urls?

Thanks!

**Comment by janko-m** [comment]
You need to generate the URLs in Ruby. If you're doing it for many records, you can SELECT only the `image_data` column, as that's the only one that's needed (though you'll probably want `id` as well). I don't know in which format is the hash supposed to be, but here is how you can generate a hash where IDs are keys and URLs are values:

```rb
@photos.select(:id, :image_data).inject({}) do |hash, photo|
  hash.merge!(photo.id => photo.image_url)
end
```

Note that usage questions should generally be asked on the Google group, GitHub issues should only be used for bug reports.
