### ISSUE TITLE
Extract metadata in custom column

### ISSUE THREAD

**Issue by Silex** [janko-m/shrine#182]
Hello,

I'm currently using CarrierWave and will very likely switch to Shrine soon, it just looks way better in pretty much every aspect, congratulations! (especially design-wise)

I store a lot of images, and I extracted the file size as a database column, which allows me to do things like `Model.where(somecondition).sum(:file_size)` at the DB level instead of the Ruby level (which would be slow).

I wondered if http://shrinerb.com/rdoc/classes/Shrine/Plugins/MetadataAttributes.html would help me there... from what I understand it's just a prettier `delegate`, am I correct? I mean by default metadata are stored in the `foo_data` column and nothing else, right? If I want to store some metadata in actual columns I need to do that in some `before_save` callback or whatever (I still use ActiveRecord, might switch to Sequel thanks to your blog post :wink:)

**Comment by janko-m** [comment]
> I'm currently using CarrierWave and will very likely switch to Shrine soon, it just looks way better in pretty much every aspect, congratulations! (especially design-wise)

Thank you!

> I wondered if http://shrinerb.com/rdoc/classes/Shrine/Plugins/MetadataAttributes.html would help me there... from what I understand it's just a prettier delegate, am I correct? I mean by default metadata are stored in the foo_data column and nothing else, right? If I want to store some metadata in actual columns I need to do that in some before_save callback or whatever (I still use ActiveRecord, might switch to Sequel thanks to your blog post 😉)

It's not a delegate, it writes metadata values to the specified attributes/columns whenever a new file is assigned. Note that only the metadata values of the original file will be synced; if you do some file processing, after the record is saved the metadata columns will still contain metadata values from the original file (it's not updated). This decision was made to prevent ambiguity when processing multiple versions, because each version has its own metadata.

**Comment by Silex** [comment]
> It's not like delegate, it writes metadata values to the specified attributes/columns whenever a new file is assigned. Note that only the metadata values of the original file will be synced; if you do some file processing, after the record is saved the metadata columns will still contain metadata values from the original file (it's not updated). This decision was made to prevent ambiguity when processing multiple versions, because each version has its own metadata.

Ah ok, so I would help in my case! Perfect then, thanks :+1:
