### ISSUE TITLE
How to use 'Backgrounding' only for some uploaders?

### ISSUE THREAD

**Issue by m1neral** [janko-m/shrine#184]
In docs only the general config:
`Generality – This setup will automatically be used for all uploaders, types of files and models.`

Thanks!

**Comment by janko-m** [comment]
The [documetation](http://shrinerb.com/rdoc/classes/Shrine/Plugins/Backgrounding.html) for the `backgrounding` plugins explains it:

> If you don't want to apply backgrounding for all uploaders, you can declare the hooks only for specific uploaders.
> 
> ```rb
> class MyUploader < Shrine
>   Attacher.promote { |data| PromoteJob.perform_async(data) }
>   Attacher.delete { |data| DeleteJob.perform_async(data) }
> end
> ```

Note that as per contribution guidelines, usage questions should be asked on the Shrine Google group, GitHub issues should be used only for bug reports.
