### ISSUE TITLE
[Pluging:Logging] Crash with json format

### ISSUE THREAD

**Issue by onomated** [janko-m/shrine#186]
Using the logging plugin with json format results in `IOError: not opened for reading` while trying to serialize the Uploader object in the data hash passed to the `_log_message_json` function.  It looks like it also fails attempting to serialize the record object as well.  In both cases, it looks like the Uploader and record object class names (as opposed to the actual objects) are intended after comparing to the output of the `:human` and `:heroku` formats.

Thanks for an awesome gem!

**Comment by janko-m** [comment]
@onomated Could you post here a minimal self-contained example that reproduces the crash? You can use the [example in CONTRIBUTING.md](https://github.com/janko-m/shrine/blob/master/CONTRIBUTING.md#appendix-b-activerecord-template) for the template.

**Comment by janko-m** [comment]
@onomated I managed to reproduce the bug, and pushed a fix. The problem was mainly in ActiveSupport overriding `#to_json` that the `logging` plugin uses, which had different behaviour than Ruby's JSON standard library.

**Comment by onomated** [comment]
@janko-m Awesome!  Thanks for the quick fix.  I'll do a better job of using the issue's template next time
