### ISSUE TITLE
Error uploading file when in daemon mode

### ISSUE THREAD

**Issue by yewness** [janko-m/shrine#188]
I have trouble uploading image file in daemon mode (keep the app running in background). Everything is fine when I run the application in console for both development and production at CentOS.
![screen shot 2017-09-26 at 8 41 43 pm](https://user-images.githubusercontent.com/14829481/30860888-70963348-a2fb-11e7-96bf-3088c40b44a6.png)

Since I need to keep the application running in the background, I changed it to daemon mode. And the uploaded image to the public folder is shown with the generated code (no image).

![screen shot 2017-09-26 at 8 42 26 pm](https://user-images.githubusercontent.com/14829481/30860887-7082bb38-a2fb-11e7-8878-0a948f4959a9.png)

When I checked the public folder, I couldn't find any image with the generated code. That means the file is lost in the ocean during the process.

After that, I tested with the local development (rails server -d) to find the error log message. This is the error message I get: 

`
Errno::EACCES (Permission denied @ dir_s_mkdir - public):
  
app/controllers/overview/users_controller.rb:16:in `update'
Started PATCH "/overview/users/2" for ::1 at 2017-09-26 20:47:16 +0800
Processing by Overview::UsersController#update as HTML
  Parameters: {"utf8"=>"‚úì", "authenticity_token"=>"ZoWnQNYiUbApbcsajGM9EiJsskfaVpwnanItYPmiNPhze1Zqf3LleH39ivUrqhSCUFIoLxR43p3jkDoV9k2H+w==", "user"=>{"full_name"=>"Yew Manager", "email"=>"yew1@gmail.com", "phone"=>"0123959234", "active"=>"true", "role"=>"manager", "address_attributes"=>{"street_address"=>"", "city"=>"", "post_code"=>"", "state"=>"W.P. Kuala Lumpur", "country"=>"MY"}, "image"=>#<ActionDispatch::Http::UploadedFile:0x007fb4cd6fb4c0 @tempfile=#<Tempfile:/var/folders/2t/527ks_8d5sq0m3lsbq45scqh0000gn/T/RackMultipart20170926-3608-1tbut0d.png>, @original_filename="20750523_10108425849896161_1829301346_n.png", @content_type="image/png", @headers="Content-Disposition: form-data; name=\"user[image]\"; filename=\"20750523_10108425849896161_1829301346_n.png\"\r\nContent-Type: image/png\r\n">}, "commit"=>"Update User", "id"=>"2"}
  [1m[36mUser Load (0.7ms)[0m  [1m[34mSELECT  "users".* FROM "users" WHERE "users"."id" = $1 ORDER BY "users"."id" ASC LIMIT $2[0m  [["id", 1], ["LIMIT", 1]]
  [1m[36mCompany Load (0.4ms)[0m  [1m[34mSELECT  "companies".* FROM "companies" WHERE "companies"."id" = $1 LIMIT $2[0m  [["id", 1], ["LIMIT", 1]]
  [1m[36mUser Load (0.4ms)[0m  [1m[34mSELECT  "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2[0m  [["id", 2], ["LIMIT", 1]]
  [1m[35m (0.2ms)[0m  [1m[35mBEGIN[0m
  [1m[35m (0.3ms)[0m  [1m[31mROLLBACK[0m
Completed 500 Internal Server Error in 21ms (ActiveRecord: 2.0ms)
`

![screen shot 2017-09-26 at 8 49 20 pm](https://user-images.githubusercontent.com/14829481/30861169-74f2a696-a2fc-11e7-96a4-c17e43cb7bca.png)

I believe that it has something to do with the wrong path routed in the daemon mode or some kind of permission that I didn't set before this. Could anyone advise on how to work on this issue?

**Comment by janko-m** [comment]
I was able to reproduce the same issue with a new Rails app in the daemon mode. The issue is that, while the `pwd` (current working directory) is equal to the application root directory when initializing the application, when requests are served it is actually set to the filesystem root when in daemon mode.

To express it in code:

```rb
# when initializing
File.expand_path("public") #=> "/Users/janko/Code/temp/rails_app/public"

# when serving requests
File.expand_path("public") #=> "/public"
```

You should be able to fix this by changing from

```rb
Shrine.storages = {
  cache: Shrine::Storage::FileSystem.new("public", prefix: "uploads/cache"),
  store: Shrine::Storage::FileSystem.new("public", prefix: "uploads/store"),
}
```

to 

```rb
Shrine.storages = {
  cache: Shrine::Storage::FileSystem.new(Rails.root.join("public"), prefix: "uploads/cache"),
  store: Shrine::Storage::FileSystem.new(Rails.root.join("public"), prefix: "uploads/store"),
}
```

I will push a fix shortly, which should make the non-expanded documented version of the code work as well, by expanding the directory path at `Shrine::Storage::FileSystem` initialization.

**Comment by yewness** [comment]
Thanks. It works well in daemon for development.

However, it still couldn't load as shown below as for production mode with or without daemon:

![screen shot 2017-10-25 at 6 59 07 pm](https://user-images.githubusercontent.com/14829481/31996003-588128d8-b9b9-11e7-859a-cd683252e708.png)

Currently the configuration is the same as before. The picture couldn't be found in the public folder. It seems that a few applications are having the same issues during production test right now. Could you assist on workaround for this issue?

**Comment by janko-m** [comment]
Could you give me more details? Is it that the picture was successfully uploaded, but retrieving it is failing with `404 Not Found`? Are you by any chance using multiple servers in production? Because FileSystem storage will work only when the application is hosted on a single server.

**Comment by yewness** [comment]
Yes, you're correct for the first one. After checking the public folder with FileZilla, the file was indeed there. There is no issue with uploading file. 

Meanwhile the chrome developer tool mentioned 404 Not found that it couldn't retrieve from the url. Does it mean it has to be exposed to the public to retrieve the picture Eg. using shrine-url?

How do I check if I'm using multiple servers? By the way, it's a CentOS dedicated server. So far, this is the only app I've deployed on this server. @janko-m

**Comment by janko-m** [comment]
@yewness Rails should automatically expose files in the `public/` folder. Could you post here your Shrine configuration and uploaders, the location of the uploaded file in the `public/` folder, and the `404 Not Found` error message?

**Comment by yewness** [comment]
This is my shrine configuration
shrine.rb
```
require "shrine"
require "shrine/storage/file_system"

Shrine.plugin :activerecord
Shrine.plugin :cached_attachment_data # for forms
Shrine.plugin :determine_mime_type

Shrine.storages = {
  cache: Shrine::Storage::FileSystem.new(Rails.root.join("public"), prefix: "uploads/cache"),
  store: Shrine::Storage::FileSystem.new(Rails.root.join("public"), prefix: "uploads/store")
}
```

uploader
```
class ImageUploader < Shrine
end
```

And then this is the log file in the production when I want to access to the public image. The current location is at /uploads/store/worker/1fe98c7868d1c2ad0d9a720319520c8b.png.
```
I, [2017-10-26T01:39:49.500779 #35100]  INFO -- : [e432af5c-e8a2-4a62-9f1b-92f95551254f] Started GET "/uploads/store/worker/1fe98c7868d1c2ad0d9a720319520c8b.png" for 210.186.251.40 at 2017-10-26 01:39:49 +0800
F, [2017-10-26T01:39:49.502495 #35100] FATAL -- : [e432af5c-e8a2-4a62-9f1b-92f95551254f]   
F, [2017-10-26T01:39:49.502689 #35100] FATAL -- : [e432af5c-e8a2-4a62-9f1b-92f95551254f] ActionController::RoutingError (No route matches [GET] "/uploads/store/worker/1fe98c7868d1c2ad0d9a720319520c8b.png"):
F, [2017-10-26T01:39:49.502810 #35100] FATAL -- : [e432af5c-e8a2-4a62-9f1b-92f95551254f]   
F, [2017-10-26T01:39:49.502907 #35100] FATAL -- : [e432af5c-e8a2-4a62-9f1b-92f95551254f] actionpack (5.1.4) lib/action_dispatch/middleware/debug_exceptions.rb:63:in `call'
```

Chrome error message
```
Failed to load resource: the server responded with a status of 404 (Not Found)
```

The image is confirmed to be uploaded into the public folder. But it cannot be opened from url.
![screen shot 2017-10-26 at 1 49 47 am](https://user-images.githubusercontent.com/14829481/32014371-7634a6d4-b9f0-11e7-8864-c7e2adcfa8a0.png)

**Comment by yewness** [comment]
I just found out the issue. The problem lies that I have not exposed my public file in production configuration.

```
  # Disable serving static files from the `/public` folder by default since
  # Apache or NGINX already handles this.
  # config.public_file_server.enabled = ENV['RAILS_SERVE_STATIC_FILES'].present?
```

So my temporary solution is
```
  config.public_file_server.enabled = true
```

And I'm able to serve the public files afterwards. After that I would configured nginx to server the static files.
