### ISSUE TITLE
filename doesn't change on update

### ISSUE THREAD

**Issue by musaffa** [janko-m/shrine#189]
Here's a basic uploader class:
```Ruby
class AttachmentUploader < Shrine
  plugin :validation_helpers

  Attacher.validate do
    validate_mime_type_inclusion %w[application/pdf application/msword], message: 'Invalid attachment file'
    validate_max_size 100.megabytes, message: 'File is too large (max is 100 MB)'
  end
end
```

For this uploader, I send a json representation of the uploaded file in the following format:
```Json
{
  "id": "349234854924394",
  "storage": "cache",
  "metadata": {
    "size": 45461,
    "filename": "foo.pdf",
    "mime_type": "application/pdf"
  }
}
```
When I create this attachment, filename `foo.pdf` is saved in the database. But If I try to update the attachment by sending a new json represention using the format above, the updated `id`, `size` and `mime_type` are properly saved except the `filename`. It remains `foo.pdf` even if a different filename is set in the metadata field.

What am I missing?

**Comment by janko-m** [comment]
@musaffa Yesterday I was able to reproduce your bug, but I somehow lost the script, and now when I tried to write the exact same script, it works correctly.

```rb
require "shrine"
require "shrine/storage/file_system"
require "active_record"
require "tmpdir"
require "stringio"

Shrine.storages = {
  cache: Shrine::Storage::FileSystem.new(Dir.tmpdir),
  store: Shrine::Storage::FileSystem.new(Dir.tmpdir),
}
Shrine.plugin :activerecord

ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Schema.define do
  create_table(:records) { |t| t.text :attachment_data }
end

class Record < ActiveRecord::Base
  include Shrine::Attachment.new(:attachment)
end

cache = Shrine.new(:cache)
uploaded_file1 = cache.upload(StringIO.new("bla"))
uploaded_file1.metadata["filename"] = "filename1.txt"
uploaded_file2 = cache.upload(StringIO.new("trololo"))
uploaded_file2.metadata["filename"] = "filename2.txt"

record = Record.new

record.attachment = uploaded_file1.to_json
record.attachment_data # => "{\"id\":\"e34a185c7fd3bb582b6563d37c58e0f0\",\"storage\":\"cache\",\"metadata\":{\"filename\":\"filename1.txt\",\"size\":3,\"mime_type\":null}}"
record.save
record.attachment_data # => "{\"id\":\"9662c2923a0a1f928aa5e677ccaae683.txt\",\"storage\":\"store\",\"metadata\":{\"filename\":\"filename1.txt\",\"size\":3,\"mime_type\":null}}"

record.attachment = uploaded_file2.to_json
record.attachment_data # => "{\"id\":\"2d51b87f58d32b7a1a8a8a6ed8415a97\",\"storage\":\"cache\",\"metadata\":{\"filename\":\"filename2.txt\",\"size\":3,\"mime_type\":null}}"
record.save
record.attachment_data # => "{\"id\":\"cff6e13b544217aac97ee192e19431c9.txt\",\"storage\":\"store\",\"metadata\":{\"filename\":\"filename2.txt\",\"size\":3,\"mime_type\":null}}"
```

I could have sworn this script is exactly the same to the one that I wrote yesterday. Could you help me to reproduce the bug?

**Comment by janko-m** [comment]
Notice that now the `size` metadata turned out to be the same (`3`), even though for the second file it's supposed to be `7`. When I re-run the same script, I get the correct `7`. Something very weird is going on. Either I haven't had enough coffee, or Shrine is acting very non-deterministic.

**Comment by musaffa** [comment]
Yeah it's weird. I will try your script after I'm back home.

**Comment by musaffa** [comment]
I've tested your script and got the same result. Shrine is just working fine. The problem was on the client side which wasn't updating the filename attribute properly inside the nested Json document representing the attachment. After testing your script and seeing expected behavior, only then it occurred to me that problem may be on the client side. Thank you for your time.
