### ISSUE TITLE
File isn't stored

### ISSUE THREAD

**Issue by askehansen** [janko-m/shrine#19]
Using basic config and attaching the file in active record. When i save the file its only stored in cache, its never uploaded to store.

I added logging to #process and i can see that its only called with the cache context

```ruby
  def process(io, context)
    Rails.logger.debug context
    nil
  end

  Photo.create(file: File.open("somefile"))
  # => {:name=>:file, :record=>#<Photo id: nil, file_data: nil, created_at: nil, updated_at: nil>, :phase=>:cache}
```

**Comment by askehansen** [comment]
I have a sample app with a failing test: https://github.com/askehansen/shrine_sample

**Comment by janko-m** [comment]
You forgot to load the plugin for your ORM, which adds appropriate lifecycle hooks:

```rb
Shrine.plugin :activerecord
```

I know that it's a bit unfortunate that you're not told about it, but I can't add a warning because Shrine's feature is that it's also usable with plain PORO models, even though it's of course a much rarer case.

**Comment by askehansen** [comment]
That did it. Thanks 👍
