### ISSUE TITLE
Shrine 2.7.0

### ISSUE THREAD

**Issue by rmaspero** [janko-m/shrine#194]
I had shrine all working fine and everything was great until I updated to Shrine 2.7.0. I was getting a 404 error when using shrine like in the GoRails part 3 tutorial. In the process I had updated some other gems as well.

Basically they way I had to fix it was to define 
gem 'roda', '~> 2.29.0'

as it had updated to 3.0.0. which appears to cause issues.

**Comment by janko-m** [comment]
@rmaspero Thanks for the report. As the matter of fact this has already been [fixed](https://github.com/janko-m/shrine/commit/35db9644790b83ea3dc03176463fde6733b94877) in master, I will be releasing a new version in 2-3 days.
