### ISSUE TITLE
Potential security issue ?

### ISSUE THREAD

**Issue by samuelkan2012** [janko-m/shrine#196]
Started PUT "/users" for 127.0.0.1 at 2017-10-18 06:37:08 +0800

Processing by Devise::RegistrationsController#update as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"[FILTERED]", "user"=>{"avatar_attributes"=>{"image"=>"", **"id"=>"43"**}, "username"=>"test", "email"=>"test@test.com", "password"=>"[FILTERED]", "password_confirmation"=>"[FILTERED]", "current_password"=>"[FILTERED]"}, "commit"=>"Save Changes"}
  User Load (1.0ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = ? ORDER BY "users"."id" ASC LIMIT ?  [["id", 1], ["LIMIT", 1]]
  User Load (1.0ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = ? LIMIT ?  [["id", 1], ["LIMIT", 1]]
**Unpermitted parameter: :id**
  Photo Load (0.0ms)  SELECT  "photos".* FROM "photos" WHERE "photos"."imageable_id" = ? AND "photos"."imageable_type" = ? LIMIT ?  [["imageable_id", 1], ["imageable_type", "User"], ["LIMIT", 1]]
   (0.0ms)  begin transaction
  **SQL (8.0ms)  DELETE FROM "photos" WHERE "photos"."id" = ?  [["id", 43]]**

When ID attribute is not permitted / omitted, the photo gets deleted although user has not entered a password

**Comment by janko-m** [comment]
@samuelkan2012 This is most likely not a Shrine security issue, since you are in control of when Shrine is called. But it's hard to tell without seeing any code.

**Comment by janko-m** [comment]
I will close this issue for now, as it doesn't seem to be a problem with Shrine. If you think this should be reopened, please provide the code that shows where the problem is.
