### ISSUE TITLE
Dynamic_storage doesn't select properly storage class

### ISSUE THREAD

**Issue by przemyslaws-iRonin** [janko-m/shrine#197]
Inside `initializers/shrine.rb` I have defined followed storages
```
Shrine.storages = {
    cache: Shrine::Storage::FileSystem.new("public", prefix: "uploads/cache"),
    store: Shrine::Storage::FileSystem.new("public", prefix: "uploads/store")
  }
```

For the cache I would like to use also storage provided by the `shrine-url` gem and use the `dynamic_storage` together with `default_storage` plugin for that.
```
plugin :dynamic_storage
storage /cache_(\w+)/ do |match|
  match[1] == 'url' ? Shrine::Storage::Url.new : Shrine.storages[:cache]
end

plugin :default_storage, cache: lambda { |record, _name|
  id = JSON.parse(record.file_data || {}.to_json)['id']
  id =~ URI::regexp(['http', 'https']) ? :cache_url : :cache
 }
```

That works when I do some hacks:
1) Data assigned to `file` need to look like below
```
{
    "id": "http://example.com/file.pdf",
    "storage": "cache_url", # I believe it should work with `"cache"` here
    "metadata": { ... }
}
```

Otherwise `file.storage` return default storage for cache, not Shrine::Storage::Url and debbuger doesn't go to followed blocks of code:
```
storage /cache_(\w+)/ do |match|
  match[1] == 'url' ? Shrine::Storage::Url.new : Shrine.storages[:cache]
end

plugin :default_storage, cache: lambda { |record, _name|
  id = JSON.parse(record.file_data || {}.to_json)['id']
  id =~ URI::regexp(['http', 'https']) ? :cache_url : :cache
 }
```

2) I need to overwrite '#uploaded?' method from https://github.com/janko-m/shrine/blob/v2.8.0/lib/shrine.rb#L238

If I leave original implementation, the `file_data` column will not be modified always. Probably it's connected with changes from the above (1) point, becauase `#uploaded?` expects `uploaded_file.storage_key == storage_key.to_s`. It means the condition should by `:cache == :cache`. In my case here is `:cache == :cache_url` or `:cache_url`==`:cache`.

I believe it should work without above hacks.

**Comment by janko-m** [comment]
The reason why using `storage: "cache"` doesn't work is because `Shrine::Attacher` (which the attachment methods delegate to) is instantiated before the attachment is assigned. This means that the `default_storage` block will be called before `record.file_data` column attribute is populated.

I would recommend doing the following, which doesn't require using `dynamic_storage` or `default_storage` plugins:

```rb
Shrine.storages = {
    cache:     Shrine::Storage::FileSystem.new("public", prefix: "uploads/cache"),
    store:     Shrine::Storage::FileSystem.new("public", prefix: "uploads/store"),
    cache_url: Shrine::Storage::Url.new
}
```
```rb
{
    "id": "http://example.com/file.pdf",
    "storage": "cache_url", # this should remain
    "metadata": { ... }
}
```
```rb
# in the controller (of course, replace "record" with the name of your model)
file_data = JSON.parse(record_params[:file_data])
record.file_attacher(cache: file_data["storage"]) 
# ...
```

Passing options to `Model#<attachment>_attacher` is only possible with the latest `master`, as I've just pushed the [commit](https://github.com/janko-m/shrine/commit/d8b763f205ef694ca34d28af84a23002e3aadfe5) that adds this feature.

Would that work for you?

**Comment by przemyslaws-iRonin** [comment]
@janko-m it works perfectly ;)

**Comment by janko-m** [comment]
Great to hear that! 😃
