### ISSUE TITLE
Rerunning store process

### ISSUE THREAD

**Issue by waffleau** [janko-m/shrine#202]
First of all love this plugin, the more I use it the more I appreciate how well designed it is!

I'm currently trying to figure out how I can re-run the store process on an image. I've made a few modifications to what I do to images in the `store` phase, but I can't see a way to easily get Shrine to re-run the steps it took to move the file from the cache to the store originally.

Something like this:

```
@image.file_attacher.reprocess!(:store)
```
or
```
@image.file_attacher.reprocess!(@image.file[:original], :store)
```
or
```
@image.file[:original].reprocess!(:store)
```

For a bit more context, here's my attempt at it, but it's deficient in a few ways, mainly that I doesn't seem to process metadata:

```
image = Image.find(image_id)

attacher = image.file_attacher
attacher.promote unless attacher.stored?

io = image.file[:original]
file = io.download

original_file = auto_orient(file)
thumbnail_file = resize_to_limit(original_file, 300, 300)

original = attacher.store!(original_file, version: :original)
original.refresh_metadata!

thumbnail = attacher.store!(thumbnail_file, version: :thumbnail)
thumbnail.refresh_metadata!

attacher.swap({ original: original, thumbnail: thumbnail })
```

Hopefully this makes sense, please let me know if you need more detail.

**Comment by janko-m** [comment]
Your attempt looks good, I'm not sure how doesn't it process metadata, it should do that correctly (without having to call `#refresh_metadata!`). Just note that by default Shrine will detect whether the IO responds to `#content_type` and copy it as the `mime_type` metadata value, so be sure to load the `determine_mime_type` plugin which determines MIME type from IO contents.

Note that if you want to keep the processing code in the uploader and maybe have things a bit simpler, you can create a separate processing action and call `#promote` again:

```rb
class ImageUploader < Shrine
  plugin :processing
  plugin :versions

  process(:reprocess) do |io, context|
    io.download

    original_file = auto_orient(file)
    thumbnail_file = resize_to_limit(original_file, 300, 300)

    { original: original_file, thumbnail: thumbnail_file }
  end
end
```
```rb
image = Image.find(image_id)

attacher = image.file_attacher
attacher.promote unless attacher.stored?

# ...

attacher.promote(action: :reprocess) # re-uploads the current uploaded file, triggering processing
```

**Comment by waffleau** [comment]
Creating a reprocess step solved my problem perfectly! Avoiding having the processing logic in two places was exactly what I wanted to do.

Thanks for your help!
