### ISSUE TITLE
Documentation for signature plugin incomplete?

### ISSUE THREAD

**Issue by aried3r** [janko-m/shrine#214]
In [`signature.rb`](https://github.com/janko-m/shrine/blob/247f75ffd2cc27051c74337dda2da17c1027d35c/lib/shrine/plugins/signature.rb#L11-L16) you can read the following:

>The plugin adds a `calculate_signature` instance and class method to
>`Shrine`, which accepts the IO object and hashing algorithm and returns
>the calculated hash.
>
>     Shrine.calculate_signature(io, :md5)
>     #=> "9a0364b9e99bb480dd25e1f0284c8555"

Maybe I misinterpret things or am just nitpicking at the documentation, but I think the documentation makes it seem that adding `plugin :signature` adds the class method to `Shrine`, but that only happens when you do `Shrine.plugin :signature` in an initializer or somewhere, *not* if you just add it to the uploader.

I am currently migrating from Carrierwave to Shrine and modifying the [`uploader_to_shrine_data`](https://github.com/janko-m/shrine/blob/master/doc/carrierwave.md#migrating-from-carrierwave) method to my needs and found out that I do not have access to `Shrine.calculate_signature` unless I add it to the global config.

I guess it makes sense to not have it in the global namespace if you only use it in a single uploader, so basically I'm just asking if it's ok if I amend the documentation?

**Comment by janko-m** [comment]
@aried3r Yes, definitely, thanks for catching that.

I think it probably makes sense to update the documentation to recommend loading the plugin globally (instead of just `plugin :signature`). We could also correct the statement "The plugin adds a `calculate_signature` instance and class method to Shrine" to "The plugin adds a `calculate_signature` instance and class method to the **uploader class**".

**Comment by aried3r** [comment]
I'll try to adapt the documentation without adding too much confusion.

On a sidenote, there's no tests for adding it globally in `signature_test.rb`, I'm not sure how you'd want that to look like, so maybe I'll leave that to you :x

**Comment by janko-m** [comment]
@aried3r Yes, the tests only call `calculate_signature` on the uploader class (`Shrine` subclass) used in tests, because the method is not actually added globally.

**Comment by aried3r** [comment]
I know, I'm just saying without a test, who knows if it works globally ;) (of course it does)

**Comment by aried3r** [comment]
Fixed in 42fc23fadc7ff26c4eeee2b1bfb2b0c229c439a4
