### ISSUE TITLE
Adding metadata to S3 storage

### ISSUE THREAD

**Issue by drummerroma** [janko-m/shrine#222]
I would like to add Cache-Control metadata to the uploads to S3 storage. 
So in my uploader I added the add_metadata plugin. 
I get the metadata information added to my database-record but I cannot see it on Amazon S3.

Code:
```
plugin :add_metadata
  add_metadata :'cache-control' do |io, context|
    'max-age=864000' # 10 days (3600*24*10 sec)
  end
```

Result in database:
`{"content":{"id":"post/56/picture/content-bb09356fa4fd725e3dc1c91a9d75c52d.png","storage":"store","metadata":{"filename":"mini_magick20171120-94328-q11rfi.png","size":303622,"mime_type":"image/png","cache-control":"max-age=864000","width":800,"height":533}}`

**Comment by hmistry** [comment]
The `add_metadata` plugin main function is to add other information to the model in the database. The plugin does not know about S3 and how to change it's settings.

To change the `Cache-Control` data for the file in S3, use the [`upload_options`](http://shrinerb.com/rdoc/classes/Shrine/Plugins/UploadOptions.html) plugin. There are 2 ways of setting it, either by storage or per file, see [here](http://shrinerb.com/rdoc/classes/Shrine/Storage/S3.html#class-Shrine::Storage::S3-label-Upload+options). The options are forwarded to the `aws-sdk-s3` gem internally so here's a list of [valid options](http://docs.aws.amazon.com/sdk-for-ruby/v3/api/Aws/S3/Object.html#put-instance_method).

**Comment by janko-m** [comment]
What @hmistry said is correct, you should use the `upload_options` plugin for setting `:cache_control`:

```rb
plugin :upload_options, store: {cache_control: "max-age=864000"}
```

**Comment by Velora** [comment]
Sorry to dig this up @janko but the above isn't working for me with S3 as my store and using the transloadit plugin. I tried setting the cache_control both globally and on a specific uploader. None of the below added cache_control metadata to my S3 objects: 

On a specific uploader:
`plugin :upload_options, store: {cache_control: "max-age=864000"}`

In  Shrine.storages definition in shrine.rb
`store: Shrine::Storage::S3.new(upload_options: { acl: "public-read", cache_control: "max-age=864000, public" }, **s3_options)`
`store: Shrine::Storage::S3.new(upload_options: { acl: "public-read", metadata: {'cache_control' => "max-age=864000, public" } }, **s3_options)`

**Comment by janko** [comment]
I'm not sure whether the configured upload options on S3 storage are used with shrine-transloadit.
