### ISSUE TITLE
Shrine::Error (must call Shrine::Attacher#url with the name of the version)

### ISSUE THREAD

**Issue by uurcankaya** [janko-m/shrine#225]
Hi,

I am trying to create versions but getting this error

`Shrine::Error (must call Shrine::Attacher#url with the name of the version):`

here is my uploader

`class ImageUploader < Shrine
 include ImageProcessing::MiniMagick
 plugin :processing
 plugin :versions
 plugin :validation_helpers

 process(:store) do |io|
    original = io.download
    size_4746 = resize_to_limit(original, 4746, 4746)
    size_2048 = resize_to_limit(size_4746, 2048, 2048)
    size_1024 = resize_to_limit(size_2048, 1024, 1024)
    size_512 = resize_to_limit(size_1024,  512, 512)
    size_300 = resize_to_limit(size_512,  300, 300)
    size_100 = resize_to_limit(size_300,  100, 100)
    {original: io, x4746: size_4746,  x2048: size_2048, x1024: size_1024, x512: size_512, x300: size_300, x100: size_100 }
  end

 Attacher.validate do
  validate_mime_type_inclusion %w[image/jpeg image/png image/gif], message: "Image must be JPEG, PNG or GIF"
  validate_max_size 4.megabytes
  end
end`

**Comment by janko-m** [comment]
It seems that somewhere you're calling `#<attachment>_url` without the version name (look at the exception stack trace to find out where). If you're generating versions, you need to provide a version name to that method, otherwise Shrine doesn't know which version it should generate the URL for.

**Comment by janko-m** [comment]
I'll close the issue for now, if you still think this is a bug feel free to reopen.
