### ISSUE TITLE
Preserve cache file and information after promote

### ISSUE THREAD

**Issue by Xosmond** [janko-m/shrine#226]
Is possible of shrine to not delete the cache file information when file is promoted to the real storage? Or to save this cache information to another field, in order to get the cache file even then the file is on the real storage?

**Comment by janko-m** [comment]
@Xosmond Certainly, you can implement that easily:

```rb
add_column :photos, :image_cache_data, :text
```
```rb
class Photo
  def image_cache=(value)
    self.image_cache_data = value ? value.to_json : nil
  end

  def image_cache
    ImageUploader.uploaded_file(image_cache_data) if image_cache_data
  end
end
```
```rb
class PhotosController < ApplicationController
  def create
    photo = Photo.new(photo_params)
    photo.image_cache = photo.image
    photo.save
  end
end
```

Now you can call `photo.image_cache` to retrieve the cached file.

**Comment by janko-m** [comment]
I will close this issue now, as usage questions should generally be asked on the Shrine google group.
