### ISSUE TITLE
Replace to other storage.

### ISSUE THREAD

**Issue by floodico** [janko-m/shrine#227]
We are created a new storage in the file system and want to upload files to this storage if they don't pass a validation, how we can do this?
What can you say about plugins for this task?

**Comment by janko-m** [comment]
There is no plugin for that, but you can easily implement this functionality:

```rb
photo = Photo.new(photos_attributes)
if photo.valid?
  photo.save
  # ...
else
  if photo.errors.key?(:image) && photo.image
    Shrine.new(:other_storage).upload(photo.image)
  end
  # ...
end
```

I will close this ticket as usage questions should generally be asked on the Shrine google group, but feel free to comment further on this ticket.

**Comment by floodico** [comment]
thanks. this functionality works
