### ISSUE TITLE
Can't load :processing plugin in model

### ISSUE THREAD

**Issue by lww** [janko-m/shrine#230]
I'm using Rails 5.1.4 with ActiveRecord and just want to build a basic processing setup but I get this error when I try to create a new object:

```
'LoadError: cannot load such file -- shrine/plugins/processing
	    from app/uploaders/teaser_uploader.rb:5:in `<class:TeaserUploader>'
	    from app/uploaders/teaser_uploader.rb:3:in `<top (required)>'
	    from app/models/program.rb:3:in `<class:Program>'
	    from app/models/program.rb:1:in `<top (required)>'
```

This is my uploader in 'app/uploaders/teaser_uploader.rb':

```
class TeaserUploader < Shrine
  plugin :processing
end
```

And my model 'program.rb'
```
class Program < ActiveRecord::Base
  include TeaserUploader[:teaser] # if i remove this line the error disappears
end
```

Uploading works if I remove the `processing` plugin and if I remove the 'include' of the Uploader in my model the error disappears.

Any advice on how to deal with this?

**Comment by janko-m** [comment]
@lww Are you using the latest version of Shrine? Do you see the `lib/shrine/plugins/processing.rb` file existing in your local `shrine` installation?

**Comment by lww** [comment]
Omg, I was using version 1.4.2... Updated to 2.8, now it's working. Thanks @janko-m
