### ISSUE TITLE
How to initialize Shrine and file system storages in Guardfile?

### ISSUE THREAD

**Issue by floodico** [janko-m/shrine#231]

**Comment by hmistry** [comment]
This is not a bug in Shrine so next time please post in [groups.google.com/groups/ruby-shrine](https://groups.google.com/forum/#!forum/ruby-shrine).

A guard file is not an initialization place to my knowledge. You may want to review what a Guardfile is and its purpose. Look in your app for places to initialize, e.g. Rails has an initializers folder for this, and there are examples and documentation to help you with initializing Shrine in [shrinerb.com](http://shrinerb.com)

If you are still having trouble getting Shrine to work by following the documented examples, then post in the google group mentioned above.

**Comment by janko-m** [comment]
@floodico You initialize the Shrine for guard the same way you initialize it in your `config/initializers/` directory. Shrine doesn't hook into Rails initialization, all of the code that you need to perform to initializer Shrine is documented in the README.

As @hmistry said, in the future please post usage questions on the Google Group.
