### ISSUE TITLE
Backgrounding and multiple Uploaders/storages not working together

### ISSUE THREAD

**Issue by jurriaan** [janko-m/shrine#234]
Hi, I'm trying to use Shrine to support multiple uploaders in an application. We have one uploader that needs to support direct uploads to S3 (using presigned URLs) since the uploaded files are pretty big. We also do some processing on them, which means we need to use the backgrounding plugin. For this uploader we use the the default :store and :cache storages

When adding another much simpler uploader in the same project (no presigned URLs, no javascript involved. This uploader is configured to upload to a different store using the cache and store configuration options in in our Sequel model like this: `include ImageUploader::Attachment.new(:header_image, cache: :image_cache, store: :image_store)
`) we hit the problem that these files were also being processed in the background as well. Which in itself isn't a big issue, but somehow it ignores the stores set in the Model and proceeds to upload the file to `:store` instead of the configured `:image_store` storage.

Do we miss some kind of configuration/setup in the background jobs? And is it possible to disable background processing for specific uploaders? (Moving the `plugin :backgrounding` call to the uploader didn't work well, it couldn't find the 'promote' method on the`Attacher`)

**Comment by hmistry** [comment]
It depends where you put the `backgrounding` plugin. If you put it in the base `Shrine` or the `ImageUploader` which subclasses Shrine, then yes it will use background processing. You can add `backgrounding` plugin to specific uploader only but adding the plugin in those uploaders only as mentioned in the docs and not in the base `Shrine` class.
Not sure why it's falling back to the default `:store/:cache` storages and not using the `ImageUploader` ones... code looks like it should get the correct Attacher's storage.

If you're still having trouble with this, it will be helpful if you can use the [Sequel template](https://github.com/janko-m/shrine/blob/master/CONTRIBUTING.md) to recreate your issue and help us be on the same page with you. Also please use the [ruby-shrine Google Group](https://groups.google.com/forum/#!forum/ruby-shrine) for questions like these, we wish to reserve Github Issues for tracking real bugs only.

**Comment by jurriaan** [comment]
@hmistry I should've read the CONTRIBUTING file, I'm sorry. Thanks for those templates, they were very helpful in creating a simple case that reproduces my issue with falling back to the default storage.

This code will show that the file is uploaded to the wrong storage:

```ruby
require "sequel"
require "shrine"
require "shrine/storage/file_system"
require "tmpdir"
require "open-uri"
require 'stringio'

Shrine.plugin :sequel
Shrine.storages = {
  cache: Shrine::Storage::FileSystem.new(Dir.tmpdir, prefix: "cache"),
  store: Shrine::Storage::FileSystem.new(Dir.tmpdir, prefix: "store"),
  image_cache: Shrine::Storage::FileSystem.new(Dir.tmpdir, prefix: "cache"),
  image_store: Shrine::Storage::FileSystem.new(Dir.tmpdir, prefix: "store"),
}
Shrine.plugin :backgrounding
Shrine::Attacher.promote do |data|
  # inline promotion instead of background for example purposes
  Shrine::Attacher.promote(data)
end

class MyUploader < Shrine
  # plugins and uploading logic
end

DB = Sequel.sqlite # SQLite memory database
DB.create_table :posts do
  primary_key :id
  column :image_data, :text
end

class Post < Sequel::Model
  include MyUploader::Attachment.new(:image, store: :image_store, cache: :image_cache)
end

post = Post.create(image: StringIO.new('foo'))

# Your code for reproducing
puts JSON(post.reload.image_data)['storage'] # outputs store instead of image_store
```

**Comment by hmistry** [comment]
It's because you're adding the backgrounding plugin to the main Shrine class and then subclassing it. It seems the background plugin defaults to :cache/:store regardless of the Attachment settings. There is a defaultStorage plugin to change the defaults... but here's a simpler way.

Here's the changes to above code that worked:
```ruby
# changed prefix paths so I can tell what's what
Shrine.storages = {
  cache: Shrine::Storage::FileSystem.new(Dir.tmpdir, prefix: "cache"),
  store: Shrine::Storage::FileSystem.new(Dir.tmpdir, prefix: "store"),
  image_cache: Shrine::Storage::FileSystem.new(Dir.tmpdir, prefix: "img_cache"),
  image_store: Shrine::Storage::FileSystem.new(Dir.tmpdir, prefix: "img_store"),
}

class OtherUploader < Shrine
  # moved the plugin from Shrine.plugin to a subclass
  # any model using this uploader will have background processing
  plugin :backgrounding
  Attacher.promote do |data|
    Attacher.promote(data)
  end
end

class MyUploader < Shrine
  # subclasses from default Shrine with no plugins
end

# your code...
puts post.image_url # => /img_store/b3c1807556c46778189afc57a6f67e7a which is what you want.
```

**Comment by hmistry** [comment]
@janko-m Shouldn't `backgrounding` plugin respect if the Attachment store/cache are changed using `include MyUploader::Attachment.new(:image, store: :image_store, cache: :image_cache)`?

**Comment by janko-m** [comment]
This was a bug in the `backgrounding` plugin, it was written before the `Shrine::Attachment.new` options were added, it should be fixed now. Thanks for reporting and reproducing with a self-contained example.

**Comment by hmistry** [comment]
@janko-m such quick service! 👍 😃

**Comment by jurriaan** [comment]
Wow, thanks @janko-m for the quick fix! 

@hmistry Forgot to mention it, but indeed, the subclassing was the problem there with backgrounding.  I guess I forgot to remove Shrine:: so it used the wrong Attacher class. The example I sent was to illustrate the problem with the wrong storage being used, should've submitted those as separate issues I guess ;)

Thanks a lot for your help and the quick fix of this issue! :)
