### ISSUE TITLE
attachment_to_shrine_data(attachment) typo?

### ISSUE THREAD

**Issue by wwwStatic** [janko-m/shrine#238]
in paperclip_shrine_synchronization.rb
  def attachment_to_shrine_data(attachment)
    {
      storage: :store,
      id: attachment.path,
      metadata: {
        size: attachment.size,
        filename: attachment.original_filename,
        content_type: attachment.content_type,
      },
    }
  end

shouldn't it be
mime_type:  attachment.content_type
instead of 
content_type: attachment.content_type
?

and thanks for this gem! It reaches the parts other file upload gems don't reach ;) - it really solves all my issues! doing a lot of migrating...

**Comment by janko-m** [comment]
Yes, it should be `mime_type` instead of `content_type`. I’ll push a fix for that.

**Comment by hmistry** [comment]
Yes. Thanks for reporting it.

**Comment by janko-m** [comment]
> and thanks for this gem! It reaches the parts other file upload gems don't reach ;) - it really solves all my issues!

I'm happy to hear that ❤️
