### ISSUE TITLE
versions not storing all width and height metatdata

### ISSUE THREAD

**Issue by wwwStatic** [janko-m/shrine#240]
Hi Janko, 
I wonder if I have found another bug?:

Say, I have

  plugin :store_dimensions
  plugin :processing
  plugin :versions
  plugin :delete_raw

  process(:store) do |io, context|
    breit = resize_to_limit(io.download, 550, nil){ |cmd| cmd.auto_orient }
    medium = resize_to_fill(breit, 300, 300, gravity: "Center")
    thumb = resize_to_fill(medium, 150, 150, gravity: "Center")
    { original: io, breit: breit, medium: medium, thumb: thumb }
  end

then the metadata in my foo_data column only stores width & height metadata for the first and last version (here original and thumb). breit and medium end up with metadata "width":null,"height":null

If I don't do the thumb version, width and height are stored for original and medium, but not breit.
If I only have 2 versions, metadata for width and height are stored fine.

The files themselves store correctly, it is just the metadata for width and height that only get stored for whatever is the first and the last version...

Kindest, Daniela

**Comment by janko-m** [comment]
@wwwStatic Hello Daniela. Thank you for the bug report, unfortunately, I'm not able to reproduce it (I used Sequel in this example but it's the same with ActiveRecord):

```rb
require "shrine"
require "shrine/storage/file_system"
require "down"
require "tmpdir"
require "image_processing/mini_magick"
require "sequel"
require "pp"

Shrine.storages = {
  cache: Shrine::Storage::FileSystem.new(Dir.tmpdir, prefix: "cache"),
  store: Shrine::Storage::FileSystem.new(Dir.tmpdir, prefix: "store"),
}

Shrine.plugin :sequel

class ImageUploader < Shrine
  include ImageProcessing::MiniMagick

  plugin :store_dimensions
  plugin :processing
  plugin :versions
  plugin :delete_raw

  process(:store) do |io, context|
    breit = resize_to_limit(io.download, 550, nil){ |cmd| cmd.auto_orient }
    medium = resize_to_fill(breit, 300, 300, gravity: "Center")
    thumb = resize_to_fill(medium, 150, 150, gravity: "Center")
    { original: io, breit: breit, medium: medium, thumb: thumb }
  end
end

DB = Sequel.sqlite
DB.create_table :photos do
  primary_key :id
  String :image_data, text: true
end

class Photo < Sequel::Model
  include ImageUploader::Attachment.new(:image)
end

file = Down.download("https://upload.wikimedia.org/wikipedia/commons/3/36/Hopetoun_falls.jpg")

photo = Photo.create(image: file)
pp photo.image
```
```
{:original=>
  #<ImageUploader::UploadedFile:0x007fe0e1187f80
   @data=
    {"id"=>"c373c927208bfe81ba01336b85a6fc50.jpg",
     "storage"=>"store",
     "metadata"=>
      {"filename"=>"Hopetoun_falls.jpg",
       "size"=>2954043,
       "mime_type"=>"image/jpeg",
       "width"=>3072,
       "height"=>2048}}>,
 :breit=>
  #<ImageUploader::UploadedFile:0x007fe0e1187d78
   @data=
    {"id"=>"2e52bc0d265d2d580c27e6dc2a25a4f9.jpg",
     "storage"=>"store",
     "metadata"=>
      {"filename"=>"mini_magick20180120-17210-9x62mi.jpg",
       "size"=>181882,
       "mime_type"=>nil,
       "width"=>550,
       "height"=>367}}>,
 :medium=>
  #<ImageUploader::UploadedFile:0x007fe0e1187af8
   @data=
    {"id"=>"2121d80e116a61b63c2b87805a044190.jpg",
     "storage"=>"store",
     "metadata"=>
      {"filename"=>"mini_magick20180120-17210-9e9blu.jpg",
       "size"=>97665,
       "mime_type"=>nil,
       "width"=>300,
       "height"=>300}}>,
 :thumb=>
  #<ImageUploader::UploadedFile:0x007fe0e11878c8
   @data=
    {"id"=>"bbbb665f147def1b79ebae9d5dee02b1.jpg",
     "storage"=>"store",
     "metadata"=>
      {"filename"=>"mini_magick20180120-17210-1r4u1d4.jpg",
       "size"=>46640,
       "mime_type"=>nil,
       "width"=>150,
       "height"=>150}}>}
```

**Comment by wwwStatic** [comment]
Thanks!

I succeed with:

  process(:store) do |io, context|
    breit = resize_to_limit(io.download, 550, nil){ |cmd| cmd.auto_orient }
    medium = resize_to_fill(io.download, 300, 300, gravity: "Center")
    thumb = resize_to_fill(io.download, 150, 150, gravity: "Center")
    { original: io, breit: breit, medium: medium, thumb: thumb }
  end

but not if I do it the way it is supposed to work, with

  process(:store) do |io, context|
    breit = resize_to_limit(io.download, 550, nil){ |cmd| cmd.auto_orient }
    medium = resize_to_fill(breit, 300, 300, gravity: "Center")
    thumb = resize_to_fill(medium, 150, 150, gravity: "Center")
    { original: io, breit: breit, medium: medium, thumb: thumb }
  end

this produces metadata width=null and height=null for breit and medium.

if I do

  process(:store) do |io, context|
    breit = resize_to_limit(io.download, 550, nil){ |cmd| cmd.auto_orient }
    medium = resize_to_fill(io.download, 300, 300, gravity: "Center")
    thumb = resize_to_fill(medium, 150, 150, gravity: "Center")
    { original: io, breit: breit, medium: medium, thumb: thumb }
  end

original, breit and thumb are ok, medium: width=null and height=null

I do use activerecord, Shrine 2.8.0 (rails 5.1.4, ruby 2.4.2). Postgres - but all of this should not matter.

**Comment by janko-m** [comment]
@wwwStatic I already told you that I'm not able to reproduce the issue, for me dimensions from all versions are extracted. Could you try reproducing the error using the Ruby script that I posted?

**Comment by wwwStatic** [comment]
That's the output:

{:original=>
  #<ImageUploader::UploadedFile:0x00007f8e4897d640
   @data=
    {"id"=>"48df306ca1e3491df187591fb22c7b65.jpg",
     "storage"=>"store",
     "metadata"=>
      {"filename"=>"Hopetoun_falls.jpg",
       "size"=>2954043,
       "mime_type"=>"image/jpeg",
       "width"=>3072,
       "height"=>2048}}>,
 :breit=>
  #<ImageUploader::UploadedFile:0x00007f8e4897d4b0
   @data=
    {"id"=>"3ac031dac21c05b43ac24db777c7cc5b.jpg",
     "storage"=>"store",
     "metadata"=>
      {"filename"=>"shrine20180120-81541-1fvcpob20180120-81541-1fyd683.jpg",
       "size"=>181859,
       "mime_type"=>nil,
       "width"=>nil,
       "height"=>nil}}>,
 :medium=>
  #<ImageUploader::UploadedFile:0x00007f8e4897d320
   @data=
    {"id"=>"402926dc00cfbb6011d83b72ad5f2dc1.jpg",
     "storage"=>"store",
     "metadata"=>
      {"filename"=>
        "shrine20180120-81541-1fvcpob20180120-81541-1fyd68320180120-81541-wnfstk.jpg",
       "size"=>97638,
       "mime_type"=>nil,
       "width"=>nil,
       "height"=>nil}}>,
 :thumb=>
  #<ImageUploader::UploadedFile:0x00007f8e4897d1b8
   @data=
    {"id"=>"1e6fac59bb22c1f7d5f8016044ae5f8b.jpg",
     "storage"=>"store",
     "metadata"=>
      {"filename"=>
        "shrine20180120-81541-1fvcpob20180120-81541-1fyd68320180120-81541-wnfstk20180120-81541-10psin1.jpg",
       "size"=>46640,
       "mime_type"=>nil,
       "width"=>150,
       "height"=>150}}>}

**Comment by janko-m** [comment]
@wwwStatic Interesting, so by executing the same script we get different results, we're getting somewhere! Try upgrading `image_processing`, `mini_magick` and `fastimage` gems to latest versions.

**Comment by wwwStatic** [comment]
Bingo! Thanks!
I only installed Shrine (2.8.0) a few days ago, and all of fastimage, image_processing, mini_magick with/after that. I wonder why gem "mini_magick" installs -v 4.3.6 (Oct 2015) and gem "image_processing" -v 0.2.4 (Oct 2015). Only fastimage installed with latest version. Had no idea that gem "gemname" with no version does not always produce latest possible version! Sorry for the bother, and thanks again!

**Comment by janko-m** [comment]
@wwwStatic Yeah, you need to run `bundle update`, otherwise it won't automatically update. So, the problem is solved?

**Comment by wwwStatic** [comment]
Absolutely! :) Thanks
