### ISSUE TITLE
Backgrounding libraries, DelayedJob

### ISSUE THREAD

**Issue by wwwStatic** [janko-m/shrine#243]
```ruby
PromoteJob = Struct.new(:data)
  def perform
    Shrine::Attacher.promote(data)
  end
end
```
should be

```ruby
PromoteJob = Struct.new(:data) do
  def perform
    Shrine::Attacher.promote(data)
  end
end
```
same with DeleteJob

enjoying your gem tremendously! thanks!

**Comment by janko-m** [comment]
@wwwStatic Thanks, updated the wiki. Btw, feel free to make updates like these directly, the wiki should be publicly editable.

> enjoying your gem tremendously! thanks!

I'm very happy to hear that, you're welcome!
