### ISSUE TITLE
Disable S3 signature

### ISSUE THREAD

**Issue by xuwupeng2000** [janko-m/shrine#245]
I have a lot of public files and I want to be able to get them without signature.
How? Why there is always signature there.

I can't cache those files.

**Comment by janko-m** [comment]
AWS S3 by default gives uploaded objects `private` access, which means these objects can *only* be retrieved with URLs that have signature. If you wish to make the objects public, you can set the `public-read` ACL on upload:

```rb
Shrine::Storage::S3.new(upload_options: {acl: "public-read"}, **other_options)
```

And generate URLs with `public: true` option.

```rb
photo.image.url(public: true)
```

You can also make `public: true` option the default:

```rb
Shrine.plugin :default_url_options, store: {public: true}
```

Note that as per contribution guidelines questions should be asked on the Shrine google group, GitHub issues should only be used for bug reports.
