### ISSUE TITLE
Shrine.logger.level value is not herited

### ISSUE THREAD

**Issue by AntoineBecquet** [janko-m/shrine#246]
A configuration problem similar to the now fixed https://github.com/janko-m/shrine/issues/57 .

Documentation says:
> Logging is by default disabled in tests, but you can enable it by setting Shrine.logger.level = Logger::INFO.

Based on this, I tried to change log level:

```ruby
Shrine.plugin :logging

class SomeUploader < Shrine; end

Shrine.logger.level = Logger::WARN
#=> 2
SomeUploader.logger.level
#=> 1
```

What happen here if I understand correctly, is that when the `:logger` option is not specified, each uploader class end up with a different `@logger` instance variable (cf. [here](https://github.com/janko-m/shrine/blob/master/lib/shrine/plugins/logging.rb#L66) and [here](https://github.com/janko-m/shrine/blob/master/lib/shrine/plugins/logging.rb#L122) ).

I expected `Shrine.logger.level` to be shared accross all uploaders. But as is, it needs to be set for each class.

I'm willing to make a pull request, but I'm not sure of the best solution:
- change `@logger` object to be uniq accross all uploaders ?
- keep one logger by class, but add an option to choose logger level at plugin initialisation ?

Thanks for your time, this gem is awesome.

**Comment by hmistry** [comment]
@AntoineBecquet 
Thank you for reporting this and we're glad you're liking the gem. I really appreciate you taking the time to present the case in such a clear and concise manner and dig into the issue.

I've confirmed this behavior even when you configure `Shrine.logger.level` before subclassing, but I'll have to defer the final design decision to @janko-m as he might have reasons for implementing it in this way. We'd also need to consider the impact, if any, this might have on existing apps. My opinion would be to have your second solution but it doesn't have to be only at plugin initialization, it just needs to be configured before subclassing. The subclass logger should inherit all options from Shrine class on subclass creation but can then be overridden individually in any of the subclasses.

@janko-m 
I've confirmed this behavior even when you set the main `Shrine.logger.level` before creating a subclass. The subclass does not inherit `Shrine` configuration. Please advise as to what behavior you'd like it to be and whether we'd need to consider any impact to existing applications.

**Comment by janko-m** [comment]
The `Shrine` subclasses should definitely inherit the logger from the superclass. In other words, this should work:

```rb
Shrine.plugin :logging
Shrine.logger.level = Logger::INFO

class ImageUploader < Shrine
end
ImageUploader.logger.level #=> Logger::INFO
```

I wouldn't like the logger object to be shared amongst subclasses, as then we don't have inheritance. In other words, I think the behaviour should stay the following:

```rb
Shrine.plugin :logging

class ImageUploader < Shrine
end

Shrine.logger.level = Logger::INFO
ImageUploader.logger.level #=> Logger::DEBUG (the default)
```
