### ISSUE TITLE
DOCS, authenticate presign endpoint in Rails.

### ISSUE THREAD

**Issue by johnunclesam** [janko-m/shrine#251]
This is not an issue but I'm opening it because I can write a PR for the docs. This topic is very sought after.

Now that https://github.com/renchap/shrine-google_cloud_storage/issues/22 is closed I'm wondering what is the best way to handle authentication for `presign` API in Rails.

I'm using it in `routes.rb` like this:

`mount ImageUploader.presign_endpoint(:cache) => "/images/presign"`

Can I use `before_action :authenticate_user` like in all the controllers?

**Can I use maybe a new controller just for presign endpoints?**

What I don't know is **how to use** this:

```ruby
plugin :presign_endpoint, presign_location: -> (request) do
  "#{SecureRandom.hex}/#{request.params["filename"]}"
end
```

**in my `presign` controller**.

How to?

This can be done also for `download_endpoint`, right?

P.S.: They say `constraints` especially with Rails 5 are very bad.

**Comment by janko-m** [comment]
> Can I use before_action :authenticate_user like in all the controllers?

Shrine's presign endpoint is a Rack application, and is separate from Rails controllers. This means you cannot use any Rails controller methods.

> I'm wondering what is the best way to handle authentication for presign API in Rails.

How you can add authentication depends on which authentication gem you are (or aren't) using. Devise has methods for authenticating on the [router level](http://www.rubydoc.info/github/plataformatec/devise/master/ActionDispatch/Routing/Mapper#authenticate-instance_method), so you should be able to use that for the mounted Rack application.

```rb
# config/routes.rb
Rails.application.routes.draw do
  authenticate do
    mount ImageUploader.presign_endpoint(:cache) => "/images/presign"
  end
end
```

> What I don't know is how to use this in my presign controller.

Shrine's presign endpoint is just a wrapper around the `#presign` method of the underlying storage. This would be more-or-less the equivalent implementation in Rails:

```rb
# config/routes.rb
Rails.application.routes.draw do
  get "/presign" => "presigns#new"
end
```
```rb
# app/controllers/presigns_controller.rb
class PresignsController < ApplicationController
  def new
    extension = File.extname(params[:filename].to_s)
    location = SecureRandom.hex + extension
    options = { content_type: Rack::Mime.mime_type(extension), ... }
    storage = Shrine.storages[:cache]

    presign = storage.presign(location, options)
    result  = { url: presign.url, fields: presign.fields, headers: presign.headers }

    headers["Cache-Control"] = "no-store" # prevent Safari from caching

    render json: result
  end
end
```

Once you've implemented it in Rails, you can use any controller helper methods for authentication. But you should also theoretically be able to call the presign application from inside the controller (though Rails doesn't make it easy):

```rb
class PresignsController < ApplicationController
  PRESIGN_ENDPOINT = ImageUploader.presign_endpoint(:cache)

  def new
    env["PATH_INFO"] = "/"
    presign_response = PRESIGN_ENDPOINT.call(env)

    response.status = presign_response[0]
    response.headers.merge!(presign_response[1])
    self.response_body = presign_response[2]
end
```

> This can be done also for `download_endpoint`, right?

The `download_endpoint` plugin depends on the `rack_response` plugin, and `rack_response` is what can be used to create your own download endpoint in Rails.

> This is not an issue but I'm opening it because I can write a PR for the docs.

Yeah, it would definitely be useful to add documentation for authentication options. I think wiki would be a good place for such a document, as it wouldn't technically be a guide about Shrine features, but rather Rails features.

Closing this here for the reasons @hmistry said.
