### ISSUE TITLE
How to override Attacher#data_attribute?

### ISSUE THREAD

**Issue by badosu** [janko-m/shrine#256]
I could not find a reference on the documentation, is there a clear way to override the data_attribute?

Also, what are the implications to other functionalities? e.g. would it change the `remote_url` plugin methods?

**Comment by badosu** [comment]
I was able to make it work using this approach:

```ruby
include FileUploader::Attachment.new(:file).tap do |a|
  a.define_method(:data_attribute) { :other_file_data }
end
```

It's not very idiomatic though, also the plugins are keeping with the previous convention, which is not a problem to me.

**Comment by janko-m** [comment]
`#data_attribute` is defined on an instance of `Shrine::Attacher` class, so you can override it in the standard way:

```rb
class Shrine::Attacher
  def data_attribute
    :"other_#{name}_data"
  end
end
```

> Also, what are the implications to other functionalities? e.g. would it change the remote_url plugin methods?

The `#remote_url` plugin saves attachment data into the specified `#data_attribute`.

If you have any further usage questions, please ask them on the Shrine Google group.

**Comment by badosu** [comment]
It does not yet solve my problem as I want just a specific attacher to use a different column.

I'll defer to the google group for further discussion.
