### ISSUE TITLE
Background helpers with ActiveJob

### ISSUE THREAD

**Issue by zamith** [janko-m/shrine#27]
When trying to use the `background_helpers` with `ActiveJob`, I got an error saying "Unsupported argument type: Symbol". Through inspection I found that Shrine is passing in the name of the attachment as a symbol, to the promote block, and `ActiveJob` does not like that.

I ended up doing this:

```ruby
Shrine::Attacher.promote do |data| 
  data["attachment"] = data["attachment"].to_s
  UploadJob.perform_later(data) 
end
```

```ruby
class UploadJob < ActiveJob::Base
  queue_as :default

  def perform(data)
    data["attachment"] = data["attachment"].to_sym
    Shrine::Attacher.promote(data)
  end
end
```

**Comment by janko-m** [comment]
Thanks a lot for reporting, I'll push a fix shortly.

**Comment by zamith** [comment]
Thanks. :+1:
