### ISSUE TITLE
Rubinius does not like "multipart: {file: image}" in tests.

### ISSUE THREAD

**Issue by jasnow** [janko-m/shrine#29]
Rubinius does not like "multipart: {file: image}" in shrine's tests.

We are getting following error 9+1 (10) times in one test file, direct_upload_test.rb, on Travis:
 * **NoMethodError: undefined method `add' on an instance of Array.**
 * https://travis-ci.org/janko-m/shrine/jobs/98983378
   * 320 runs, 517 assertions, 1 failures, 9 errors, 0 skips

To reproduce it, I change my rvm locally to "rvm install rbx-2.9" and ran "bundle"/"rake" and got same results.

You can also run this: "rake test TEST=test/plugin/direct_upload_test.rb".

Question: Is there another way to specify the "multipart: {file: image}" in this file: test/plugin/direct_upload_test.rb"?

Here is the line in the rack-test_app gem: lib/rack/test_app.rb:230:  * v.is_a?(::File) ? mp.add_file(k, v) : mp.add(k, v.to_s)

**Comment by janko-m** [comment]
Thanks, I've already isolated the bug before, and raised an issue on Rubinius (https://github.com/rubinius/rubinius/issues/3544). I've tried to see if that part in rack-test_app can be written a bit differently, but it would have to be a big change.

I will make these tests pending for Rubinius for now, until it is resolved and a new Rubinius version is released.

**Comment by jasnow** [comment]
Thanks for your response.
