### ISSUE TITLE
Metadata extraction

### ISSUE THREAD

**Issue by davidterranova** [janko-m/shrine#30]
Hi,
I am following your documentation to extract more metadata (exif) but I face a strange behavior.
In the `extract_metadata` method, the `io` object does not have a `path` method, neither a valid `tempfile` object.
Using the following code, I get a `undefined method 'tempfile' for #<ImageUploader::UploadedFile`.
Any advice / Idea ? 

```ruby
class ImageUploader

...

  def extract_metadata(io, context)
    metadata = super
    metadata['exif'] = Exif::Data.new(io.tempfile.path)
    metadata
  end

...

end
```
using Rails 4.2.5, ActiveRecord and the following plugins:
- Shrine.plugin :active record
- Shrine.plugin :logging, logger: Rails.logger
- Shrine.plugin :direct_upload, presign: true
- Shrine.plugin :determine_mime_type
- plugin :remove_attachment
-  plugin :store_dimensions
-  plugin :validation_helpers
-  plugin :pretty_location
-  plugin :versions, names: [:original]

Thank you

**Comment by janko-m** [comment]
The reason for this is because `#extract_metadata` is being called twice, once for caching (where `io` is the original file uploaded) and second time for storing (where `io` is the cached `Shrine::UploadedFile` instance). A quick workaround is adding a conditional:

```rb
def extract_metadata(io, context)
  if context[:phase] == :cache
    metadata = super
    metadata['exif'] = Exif::Data.new(io.tempfile.path)
    metadata
  else
    super
  end
end
```

The permanent solution would be to make `#extract_metadata` called only when caching, and that for all other phases the metadata is just inherited from the `UploadedFile` directly. I will try to implement that soon.

**Comment by davidterranova** [comment]
Thanks for the reply,

I also found that the `#extract_metadata` is being called two times.
Unfortunately your solution doesn't work. In fact when the `#extract_metadata` is called for the second time, it overwrites the previously written metadata.

I found a temporary / dirty solution :

```ruby
def extract_metadata(io, context)
  metadata = super
  if context[:phase] == :cache
    metadata['exif'] = Exif::Data.new(io.tempfile.path)
  elsif context[:phase] == :store
    metadata.merge!(JSON.parse(context[:record][:image_data], {symbolize_names: true})[:metadata])
  end
  metadata
end
```

As mentioned, the best solution would be to call the `#extract_metadata` only once, curing the phase **cache**

Best regards,
