### ISSUE TITLE
Processing with backgrounding

### ISSUE THREAD

**Issue by zamith** [janko-m/shrine#34]
I'm using the background jobs plugin to promote from cache to store in a background job. However, when combined with image processing, it simply fails, I think because the `promote` method never calls the `process` method.

If I do the resizing in the `cache` phase it works fine, and if I disable the background jobs plugin and do the processing in the `store` phase it also works fine.

Is this a bug, or am I just using it wrongly?

**Comment by janko-m** [comment]
Could you post the code of you uploader class? It should work properly, because `Attacher#promote` calls `Shrine#upload`, which always calls `Shrine#process`. Is there some error that the background job raises? Also, does the file get stored if you disable processing?

**Comment by zamith** [comment]
Here's all the relevant (I think) code: https://gist.github.com/zamith/e6cc43c5021a8988c0b3

I see no error in the background job, and yes, everything is stored correctly without the processing.

**Comment by janko-m** [comment]
I cannot reproduce the bug with Shrine 1.1. Did you try `puts`-ing in `Shrine#process` to see if it even gets called?

It would be great if you could take a look at the below script, and try to figure out what is different in your Rails app, and update the script so that it fails. If I have a self-contained script that fails, I can find the root of the issue.

```rb
require "active_record"
require "active_job"
require "shrine"
require "shrine/storage/file_system"
require "image_processing/mini_magick"
require "open-uri"

ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.raise_in_transactional_callbacks = true
ActiveRecord::Migration.class_eval do
  create_table :users do |t|
    t.text :avatar_data
  end
end

ActiveJob::Base.queue_adapter = :inline

Shrine.storages = {
  cache: Shrine::Storage::FileSystem.new("uploads/cache"),
  store: Shrine::Storage::FileSystem.new("uploads/store"),
}

Shrine.plugin :activerecord
Shrine.plugin :pretty_location
Shrine.plugin :backgrounding
Shrine::Attacher.promote { |data| UploadJob.perform_later(data) }

class UploadJob < ActiveJob::Base
  queue_as :default

  def perform(data)
    Shrine::Attacher.promote(data)
  end
end

class AvatarUploader < Shrine
  include ImageProcessing::MiniMagick

  def generate_location(io, _context)
    "avatars/#{super}"
  end

  def process(io, context)
    if context[:phase] == :store
      resize_to_limit(io, 30, 30)
    end
  end
end

class User < ActiveRecord::Base
  include AvatarUploader[:avatar]
end

user = User.create(avatar: open("https://cdn.tutsplus.com/net/uploads/2013/08/github-collab-retina-preview.gif"))
puts user.avatar.metadata # shows large filesize
sleep 2
puts user.reload.avatar.metadata # shows small filesize -- proof that it was resized
```

**Comment by zamith** [comment]
I'll try using Shrine 1.1. Also, shouldn't it be `io.download`, instead of `io`?

**Comment by janko-m** [comment]
It should work just with `io`, but I think that's accidental, for optimal performance and preserving of file extension it's better to use `resize_to_limit!(io.download, 30, 30)`.

**Comment by zamith** [comment]
I've updated it, and it is working. Maybe it was that sleep of 2 seconds that was misleading me, maybe I was checking to soon. Thanks.
