### ISSUE TITLE
strip

### ISSUE THREAD

**Issue by dcalixto** [janko-m/shrine#4]
firt great work, and i'm looking to move from carrierwave to shrine.

just one doubt, can i change the image quality to reduce the size of image on upload?

a exemple with minimagick and carrierwave strip method
module CarrierWave
  module MiniMagick
    # Strips out all embedded information from the image
    def strip
      manipulate! do |img|
        img.strip
        img = yield(img) if block_given?
        img
      end
    end

    # Reduces the quality of the image to the percentage given
    def quality(percentage)
      manipulate! do |img|
        img.quality(percentage.to_s)
        img = yield(img) if block_given?
        img
      end
    end
  end
end

**Comment by janko-m** [comment]
Hey Daniel,

Image processing in Shrine is done using the [image_processing](https://github.com/janko-m/image_processing) gem directly. With it you can do something like this:

```rb
require "image_processing/mini_magick"

class ImageUploader < Shrine
  include ImageProcessing::MiniMagick

  def process(io, context)
    if context[:phase] == :store
      with_minimagick do |image| # yields a MiniMagick::Image
        image.quality("...")
      end
    end
  end
end
```

The `with_minimagick` call returns the processed file, so depending on whether you're generating thumbnails you can store the processed file in a variable and use it for later.

Note that, as per contribution guidelines, it would be great if in future you ask usage questions on the Google Group, and use GitHub issues only for bugs and pull requests. Thanks!
