### ISSUE TITLE
Default image from disk

### ISSUE THREAD

**Issue by zamith** [janko-m/shrine#51]
Is it possible to define a default image in shrine?

The intended behaviour would be something like:

```ruby
image_tag(user.avatar_url || default_user_avatar)
```

But without having to do this every time (or having to do this on the `User` model). It would also be helpful if it integrated with the versions plugin.

**Comment by janko-m** [comment]
If you only want to have a "default URL", you can use the `:default_url` plugin:

```rb
class ImageUploader < Shrine
  plugin :default_url do |context|
    "/path/to/default/image.jpg"
  end
end
```
```rb
user.avatar #=> nil
user.avatar_url #=> "/path/to/default/image.jpg"
```

**Comment by janko-m** [comment]
To add on the versions plugin, if you ask for URL of specific version, the version name is included in `context`:

```rb
class ImageUploader < Shrine
  plugin :default_url do |context|
    "/path/to/default/#{context[:version]}.jpg"
  end
end
```
```rb
user.avatar_url(:small) #=> "/path/to/default/small.jpg"
user.avatar_url(:medium) #=> "/path/to/default/medium.jpg"
```

**Comment by zamith** [comment]
Thanks. :+1: I looked for something with this name in a list of plugins but it wasn't there. Maybe it was outdated.

Is there any list for plugins other than looking at the source code?

**Comment by janko-m** [comment]
Yes! Shrine has a [website](http://shrinerb.com), which includes a list and descriptions of all plugins, helpful guides and RDocs, and links to external plugins/storages.

**Comment by zamith** [comment]
Nice, that's it. Then I ended up in some old resource maybe. Sorry for the trouble.

**Comment by woto** [comment]
JFYI since that time looks like API have been changed. The actual way is described here: https://shrinerb.com/docs/plugins/default_url
