### ISSUE TITLE
Empty files after version processing

### ISSUE THREAD

**Issue by robertasg** [janko-m/shrine#56]
Hi.

Basically, I come up with empty files after processing the file and returning versions by the example. I think the issue is that the files are not rewinded after being passed to MiniMagick. Since it works if I rewind the file cursor, or pass a new tempfile to one of the MiniMagick processing methods. I guess adding a rewind call for the versioned files when storing should do the trick?

**Comment by janko-m** [comment]
I see, image_processing isn't rewinding the file after doing the processing, strange that I've missed that. I'll push a fix shortly.

**Comment by robertasg** [comment]
Nice, thanks!
