### ISSUE TITLE
Let's add Travis CI

### ISSUE THREAD

**Issue by kuraga** [janko-m/shrine#6]
Good day! Thanks for your work!

Let's add Travis CI to Shrine's repositories?

**Comment by kuraga** [comment]
Thanks!

**Comment by janko-m** [comment]
I forgot that you always need ~20 commits to get the CI working :). I will open a separate PR for fixing the test failures when I find time.

**Comment by janko-m** [comment]
Added in https://github.com/janko-m/shrine/pull/11.
