### ISSUE TITLE
Cannot load such file -- down/version

### ISSUE THREAD

**Issue by eduardodeoh** [janko-m/shrine#68]
Hi @janko-m 

I'm trying your gem and get this error:

`/Users/eduardo/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.rc1/lib/active_support/dependencies.rb:293:in `require': cannot load such file -- down/version (LoadError)`

I'm using Rails 5.0.0.rc1. Any help?

**Comment by janko-m** [comment]
Hey, sorry, it was a faulty release of the Down gem, just do `bundle update down`.

**Comment by eduardodeoh** [comment]
Thanks!
