### ISSUE TITLE
regenerating versions doesn't work

### ISSUE THREAD

**Issue by kschaper** [janko-m/shrine#71]
Hi Janko,

first of all thanks a lot for the great Shrine, I really like it.

I tried to follow the guide on Reprocessing Versions. It doesn't work because `Shrine::Plugins::Activerecord::AttacherMethods.swap` must not be private. This is in my Rake task:

```ruby
Photo.all.each do |photo|
  attacher, attachment = photo.image_attacher, photo.image
  if attacher.stored?
    file_500 = resize_to_limit(attachment[:large].download, 500, 500)
    medium = attacher.store!(file_500, version: :medium)
    attacher.swap(attachment.merge(medium: medium))
  end
end
```

Sorry I can't provide a pull request right now.

Cheers
Kai

**Comment by janko-m** [comment]
Thanks for reporting, I will fix this shortly.

In the meanwhile, you can use `attacher.send(:swap, ...)`. Also, I don't know how many Photo records you have, but it's generally better to use `Photo.find_each`.

**Comment by janko-m** [comment]
I named the commit message wrong, it actually does make `Attacher#swap` public 😄

**Comment by kschaper** [comment]
Thank you for fixing this so quickly.

At the moment I'm playing around with just a couple of files. So `Photo.all.each` work fine for now. But I'm aware that `find_each` is a better way to deal with thousands of records.
