### ISSUE TITLE
IRC? Gitter?

### ISSUE THREAD

**Issue by jnylen** [janko-m/shrine#75]
Hi Janko,
Any ideas surrounding creating a IRC channel (Freenode?) or Gitter to discuss stuff regarding Shrine?

**Comment by janko-m** [comment]
I setup a [Google group](https://groups.google.com/forum/#!forum/ruby-shrine) for discussions and questions regarding Shrine. I know that some projects use IRC or Gitter, but I think that with a Google group people form their questions and concerns better. Is that feasible?

**Comment by jnylen** [comment]
Apparently I completely missed that link somehow.
That look fine ;)
