### ISSUE TITLE
Shrine::InvalidFile Issue for Polymorphic association (multiple files)

### ISSUE THREAD

**Issue by kaleemullah** [janko-m/shrine#78]
Hello,

I'm trying to upload multiple files (polymorphic association) on cloudinary but getting following issue:
`
  A Shrine::InvalidFile occurred in project_events#create:
  [#<ActionDispatch::Http::UploadedFile:0x007f8ff9b84cd8 @tempfile=#<Tempfile:/var/folders/x7/388gqf5n69d42wr2_38nnp_w0000gn/T/RackMultipart20160823-6210-17lqioo.png>, @original_filename="apartment.png", @content_type="image/png", @headers="Content-Disposition: form-data; name=\"project_event[photos_attributes][0][image][]\"; filename=\"apartment.png\"\r\nContent-Type: image/png\r\n">, #<ActionDispatch::Http::UploadedFile:0x007f8ff9b84c10 @tempfile=#<Tempfile:/var/folders/x7/388gqf5n69d42wr2_38nnp_w0000gn/T/RackMultipart20160823-6210-ddmbfz.png>, @original_filename="arrow_empty_to_ltr.png", @content_type="image/png", @headers="Content-Disposition: form-data; name=\"project_event[photos_attributes][0][image][]\"; filename=\"arrow_empty_to_ltr.png\"\r\nContent-Type: image/png\r\n">] is not a valid IO object (it doesn't respond to #read, #eof?, #rewind, #close)`

**Controller:**
```
      def new
        @project_event = ProjectEvent.new
        @project_event.photos.build
      end

      def create
        @project_event = ProjectEvent.new(permitted_params)
        @project_event.save
      end

      def permitted_params
        params.require(:project_event).permit!
      end

```

**View:(using [ActiveAdmin](https://github.com/activeadmin/activeadmin) and Formatastic gem)**

```
    form html: { enctype: "multipart/form-data" } do |f|
      f.semantic_errors

      f.inputs for: [:photos] do |photo_form|
        photo_form.input :image, as: :file, label: 'Photos', input_html: { multiple: true }
      end

      f.actions
    end
```

**Model: project_event.rb**

```
class ProjectEvent < ActiveRecord::Base
  has_many    :photos, as: :photoable, class_name: 'Photo', dependent: :destroy

  accepts_nested_attributes_for :photos, allow_destroy: true

end
```

**Model: Photo.rb**

```
class Photo < ActiveRecord::Base
  include ImageUploader[:image]
end

```

**Uploader:**
```
class ImageUploader < Shrine
end
```

**shrine.rb**

```
require "cloudinary"
require "shrine/storage/cloudinary"


Shrine.storages = {
  cache: Shrine::Storage::Cloudinary.new(store_data: true, prefix: "cache"), # for direct uploads
  store: Shrine::Storage::Cloudinary.new(store_data: true),
}

Shrine.plugin :activerecord
Shrine.plugin :cached_attachment_data # for forms
Shrine.plugin :determine_mime_type
Shrine.plugin :backgrounding
Shrine.plugin :delete_promoted

Shrine::Attacher.promote { |data| PromoteJob.perform_async(data) }
Shrine::Attacher.delete { |data| DeleteJob.perform_async(data) }
```

**Full Request Parameters**
`  Parameters: {"utf8"=>"✓", "authenticity_token"=>"PE7ti+d9466ZsHPWAnNfrLF91vPRA3popcsaTiiEzjIUIuhgC2yHnDkOk8hocIm4iPyxZweM4NMjKi5zDKGX2A==", "project_event"=>{"project_id"=>"3", "event_type"=>"", "event_date(1i)"=>"1951", "event_date(2i)"=>"3", "event_date(3i)"=>"3", "progress"=>"", "notes"=>"", "source"=>"", "internal"=>"1", "photos_attributes"=>{"0"=>{"image"=>[#<ActionDispatch::Http::UploadedFile:0x007f8ff9b84cd8 @tempfile=#<Tempfile:/var/folders/x7/388gqf5n69d42wr2_38nnp_w0000gn/T/RackMultipart20160823-6210-17lqioo.png>, @original_filename="apartment.png", @content_type="image/png", @headers="Content-Disposition: form-data; name=\"project_event[photos_attributes][0][image][]\"; filename=\"apartment.png\"\r\nContent-Type: image/png\r\n">, #<ActionDispatch::Http::UploadedFile:0x007f8ff9b84c10 @tempfile=#<Tempfile:/var/folders/x7/388gqf5n69d42wr2_38nnp_w0000gn/T/RackMultipart20160823-6210-ddmbfz.png>, @original_filename="arrow_empty_to_ltr.png", @content_type="image/png", @headers="Content-Disposition: form-data; name=\"project_event[photos_attributes][0][image][]\"; filename=\"arrow_empty_to_ltr.png\"\r\nContent-Type: image/png\r\n">]}}}, "commit"=>"Create Project event"}`

@janko-m  Can you please help me out? Thank you.

**Comment by janko-m** [comment]
You can see that the attachment was received as an array of `ActionDispatch::Http::UploadedFile`, because your file input is marked with `multiple: true`.

However, Shrine's attachment attribute only accepts single files, so you need to remove `multiple: true` from your file field.

**Comment by kaleemullah** [comment]
Thanks for looking into it but I want to upload multiple files in a single shot, can I do that somehow with shrine ?

**Comment by janko-m** [comment]
In that case you can just have a separate multiple file input field, and then in your controller manually split it into nested attributes. Something like the following should work:

```rb
file_field_tag 'files', multiple: true
```
```rb
def create
  project_event_params = permitted_params
  project_event_params["photos_attributes"] = {}
  params["files"].each_with_index { |file, idx| project_event_params["photos_attributes"][idx] = {image: file} }
  @project_event = ProjectEvent.new(project_event_params)
  @project_event.save
end
```

**Comment by janko-m** [comment]
I will close this as it isn't a bug with Shrine, feel free to ask any further questions on the [Shrine Google group](https://groups.google.com/forum/#!forum/ruby-shrine).

**Comment by kaleemullah** [comment]
It works! Thank you so much.

**Comment by ckrampanis** [comment]
@kaleemullah  can you share the solution? hay have the same problem

**Comment by kaleemullah** [comment]
@ckrampanis Sure, here it is:
```
= form.fields_for :photos do |photo_form|
  = photo_form.input :image, label: false, input_html: { type: 'hidden', value: photo_form.object.cached_image_data, multiple: true, accept: "image/x-png, image/jpeg" }
  = photo_form.input :image, label: false, input_html: { type: 'file', multiple: true, accept: "image/x-png, image/jpeg" }
```

Let me know how it goes.

**Comment by AlexVentura** [comment]
What if I want to upload only and exactly just three images? Should I add three different `file_filed` in my model, view, and so on?

Any suggestion will come in handy!
Thanks in advance!
