### ISSUE TITLE
Trying to chmod /tmp

### ISSUE THREAD

**Issue by katafrakt** [janko-m/shrine#80]
This is more a question than issue.

I was checking how Shrine 2.3.0 behaves with `hanami-shrine` gem and I was quite surprised that the tests failed right away with this:

```
/home/katafrakt/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/shrine-2.3.0/lib/shrine/storage/file_system.rb:111:in `chmod': Operation not permitted @ chmod_internal - /tmp (Errno::EPERM)
	from /home/katafrakt/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/shrine-2.3.0/lib/shrine/storage/file_system.rb:111:in `chmod'
	from /home/katafrakt/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/shrine-2.3.0/lib/shrine/storage/file_system.rb:111:in `initialize'
```

It turned out that FileSystem plugin now [tries to `chmod`](https://github.com/janko-m/shrine/blob/master/lib/shrine/storage/file_system.rb#L111) the `/tmp` directory. This happened because I used this in configuration:

```ruby
cache: Shrine::Storage::FileSystem.new(Dir.tmpdir)
```

The comment in the file is a bit misleading, saying that:

> Changes the UNIX permissions of created directories (default is 0755).

Of course everything works if I set a config to, for example, `Dir.mktmpdir`. But now my question is:

Since this is kind of a breaking change, is it expected? Or maybe chmodding is not that important and can be wrapped in `rescue` from `Errno::EPERM`? I'm okay if you consider it expected behaviour, I just want to know it.

**Comment by janko-m** [comment]
Thank you for reporting this. I agree, this is definitely not the correct behaviour. I think it's best to `chmod` only newly created directories, so if the storage is initialized with a directory that already exists, no `chmod`ing should be performed. I will go ahead an make that change, and release a new version.
