### ISSUE TITLE
Support for uploading with S3 Transfer Acceleration?

### ISSUE THREAD

**Issue by jonathanhoskin** [janko-m/shrine#81]
As per the S3 docs, do you know of and/or plan to support enabling S3 Transfer Acceleration?
http://docs.aws.amazon.com/AmazonS3/latest/dev/transfer-acceleration.html

I've attempted to just add the `:use_accelerate_endpoint` boolean to Shrine's S3 client options ([as per the AWS docs](http://docs.aws.amazon.com/sdkforruby/api/Aws/S3/Client.html#initialize-instance_method)), but it still generates the non-accelerated version of the URL when generating presigned URLs. 

I also added the `host` option, but I think this only affects download URLs, not the presigned URLs for uploads right?

```
  s3_options = {
    region: 'ap-southeast-2',
    bucket: 'my-bucket',
    host = 'my-bucket.s3-accelerate.amazonaws.com',
    use_accelerate_endpoint: true
  }

  Shrine.storages = {
    cache: Shrine::Storage::S3.new(prefix: "#{Rails.env}/cache", **s3_options),
    store: Shrine::Storage::S3.new(prefix: "#{Rails.env}/store", **s3_options)
  }
```

This could well be a limitation of the AWS Ruby SDK, I haven't dug all the way to the bottom to investigate further.

Any thoughts? Happy to contribute a PR if you think there is scope for it. Thanks in advance!

**Edit**: Just confirming ahead of time; Yep, I've enabled the feature on my buckets.

**Comment by janko-m** [comment]
The correct way to do it should be to include `use_accelerate_endpoint: true` in the `:upload_options` parameter:

```rb
Shrine::Storage::S3.new(upload_options: {use_accelerate_endpoint: true}, ...)
```

As per the [Shrine::Storage::S3 documentation](http://shrinerb.com/rdoc/classes/Shrine/Storage/S3.html), it will be passed both when uploading and generating the presigned URL.

However, this will still generate the non-accelerated download URL, but I assume you want it to use the accelerated host; let me know if that should be the default behaviour.

The other problem is that `Aws::S3::Object#presigned_post` doesn't seem to support the `:use_accelerate_endpoint` (looking from the documentation), and in that case I don't know how to generate presigned URLs using the accelerate host. `Aws::S3::Client` also accepts the `:endpoint` option, maybe that could globally set the accelerate host, although I haven't tested it.

These are some ideas that popped to head now, though I don't have time at the moment to go deeper in it. If we come up with a solution that uses accelerate endpoint in all of the elements (normal uploading, presigned uploading and download URLs), I definitely want to make it easier to setup in Shrine, either by sending a PR to aws-sdk gem, or by solving it in Shrine.

**Comment by jonathanhoskin** [comment]
Hi @janko-m, thanks for the prompt response!

### Upload options ###
Indeed that makes sense; I did try to use `:use_accelerate_endpoint` inside `: upload_options`, but I get an exception because, as you mentioned, it's just not supported:

```
Started GET "/file-uploads/cache/presign" for ::1 at 2016-09-20 11:56:17 +1200

NoMethodError (undefined method `use_accelerate_endpoint' for #<Aws::S3::PresignedPost:0x007fa8f9555600>):
  aws-sdk-resources (2.5.7) lib/aws-sdk-resources/services/s3/presigned_post.rb:224:in `block in initialize'
  aws-sdk-resources (2.5.7) lib/aws-sdk-resources/services/s3/presigned_post.rb:220:in `each'
  aws-sdk-resources (2.5.7) lib/aws-sdk-resources/services/s3/presigned_post.rb:220:in `initialize'
  aws-sdk-resources (2.5.7) lib/aws-sdk-resources/services/s3/object.rb:128:in `new'
  aws-sdk-resources (2.5.7) lib/aws-sdk-resources/services/s3/object.rb:128:in `presigned_post'
  shrine (2.3.1) lib/shrine/storage/s3.rb:255:in `presign'
  shrine (2.3.1) lib/shrine/plugins/direct_upload.rb:281:in `generate_real_presign'
  shrine (2.3.1) lib/shrine/plugins/direct_upload.rb:273:in `generate_presign'
  shrine (2.3.1) lib/shrine/plugins/direct_upload.rb:215:in `block (3 levels) in <class:App>'
```

### Endpoint ###
Thanks for the head-up on that option, I've just added `:endpoint` to the options and this gets it working for the presigned URL:

This:
```
Shrine::Storage::S3.new(endpoint: 'https://s3-accelerate.amazonaws.com', ...)
```
Produces this JSON in the presign GET:
```
{ "url": "https://[my-bucket].s3-accelerate.amazonaws.com", "fields": {...} }
```
This is probably good enough for me for now, what do you think?

**Comment by janko-m** [comment]
@jonathanhoskin Great! Yes, this definitely looks like the right solution, as it automatically applies to regular and presigned uploads, as well as download URLs. I will update the documentation.

**Comment by janko** [comment]
Setting the `:endpoint` seems to cause `Aws::S3::Errors::SignatureDoesNotMatch` now. The correct way to use transfer acceleration is to set the `:use_accelerate_endpoint` client option:

```rb
Shrine::Storage::S3.new(use_accelerate_endpoint: true, **other_options)
```

Just posting for future reference.

**Comment by jclusso** [comment]
Not sure why but `use_accelerate_endpoint` doesn't work for me. Changes nothing. Using `endpoint` like @jonathanhoskin did does though.

**Comment by jclusso** [comment]
@janko I previously thought this was working with `endpoint`. Uploads appear to work fine but for some reason some larger files throw the `Aws::S3::Errors::SignatureDoesNotMatch` during promotion when I try and call `refresh_metadata!`. What's weird is some files worked though.
