### ISSUE TITLE
Avoid use of Model#after_commit, #after_destroy_commit

### ISSUE THREAD

**Issue by jeremyevans** [janko-m/shrine#83]
Model#after_commit can lead to large memory use during transactions, as they cause Sequel to keep the model instance in memory.  Switch:

```ruby
            def after_commit
              super
              #{@name}_attacher.finalize if #{@name}_attacher.attached?
            end
```

to:

```ruby
            def after_save
              super
              db.after_commit{#{@name}_attacher.finalize} if #{@name}_attacher.attached?
            end
```

The same is true for #after_destroy_commit, but since you are running code regardless in that case, it doesn't save you much currently.  I am planning on moving the model after commit/rollback hooks to a plugin in Sequel 5, so switching after_destroy_commit to calling db.after_commit in after_destroy would be a good change to make as well.

**Comment by janko-m** [comment]
@jeremyevans Thanks for letting me know! For the `after_destroy` hook I will probably add a conditional to call `#{name}_attacher.destroy` only if a file is attached. I will make the changes shortly.
