### ISSUE TITLE
How can we test shrine?

### ISSUE THREAD

**Issue by MrWilhelm** [janko-m/shrine#85]
Hello, I like this gem but I want to find out how can I test this with MiniTest, can you provide some example? I'm thinking about to use it for an Api.

**Comment by aitbw** [comment]
I think it would be better to ask these kind of questions over [here](https://groups.google.com/forum/#!forum/ruby-shrine). This should be only used to report bugs or issues.

**Comment by janko-m** [comment]
@MrWilhelm I intend to write a guide about testing at some point, but you can also just try it yourself, and ask any specific questions on the google group. Some upfront tips: https://github.com/janko-m/shrine/issues/82, [shrine-memory](https://github.com/janko-m/shrine-memory).

**Comment by janko-m** [comment]
@MrWilhelm To follow-up, I've written [Testing with Shrine](http://shrinerb.com/rdoc/files/doc/testing_md.html) guide, which will hopefully give you some useful tips for testing.
