### ISSUE TITLE
No such file or directory @ dir_s_rmdir

### ISSUE THREAD

**Issue by mma7** [janko-m/shrine#87]
Hello everyone i am trying to use shrine for image uploading.
I deleted some uploaded files manually and when i try to delete the associated record in the datatabse i get the following error:

```
Errno::ENOENT in OffersController#destroy
No such file or directory @ dir_s_rmdir - public/uploads/store/90e08a9f86e055f45ca1bd9938f323b9.jpeg
```
Here is my code:

**Models:**
```
class Offer < ApplicationRecord
  has_many :photos, as: :imageable, dependent: :destroy
end
```
```
class Photo < ApplicationRecord
  include ImageUploader[:image]
  belongs_to :imageable, polymorphic: true
end
```

**image_uploader.rb:**
```
require "image_processing/mini_magick"

class ImageUploader < Shrine

  include ImageProcessing::MiniMagick
  plugin :processing
  plugin :determine_mime_type
  plugin :validation_helpers
  plugin :versions

  Attacher.validate do
    validate_max_size 5.megabytes, message: 'is too large (max is 5 MB)'
    validate_mime_type_inclusion ['image/jpg', 'image/jpeg', 'image/png', 'image/gif']
  end

  process(:store) do |io, context|
    thumb = resize_to_limit!(io.download, 180, 120)
    { original: io, thumb: thumb }
  end
end
```

**intitilizer:**
```
require "shrine"
require "shrine/storage/file_system"

Shrine.storages = {
  cache: Shrine::Storage::FileSystem.new("public", prefix: "uploads/cache"),
  store: Shrine::Storage::FileSystem.new("public", prefix: "uploads/store"),

}

Shrine.plugin :activerecord
Shrine.plugin :logging, logger: Rails.logger
Shrine.plugin :direct_upload, max_size: 5*1024*1024 # 5 MB
Shrine::UploadEndpoint.use FineUploaderResponse
```

I don't know if this is a bug! i don't see why an exception should be thrown! If a file deson't exist then it it dosen't need to be deleted that's all.
thanks in advance.

**Comment by mma7** [comment]
This somehow seems to be fixed by adding the "delete_raw" plugin.
Every offer record is deleted automatically!
But why?

**Comment by janko-m** [comment]
@mma7 The FileSystem storage will raise an error when attempting to delete a file that doesn't exist. That is the general behaviour of all storages, any errors that happen on deleting are reported.

However, although in the past I left this behaviour on purpose, I think I agree now that we shouldn't fail if the file is simply missing, because it doesn't seem to help in any case and makes testing more difficult. I will try to push a fix by the end of the week.

**Comment by mma7** [comment]
Thanks for your quick reply.
And thanks for the Gem.
Good luck.

**Comment by janko-m** [comment]
I will leave this open, as it's still an unresolved issue :wink:
