### ISSUE TITLE
File upload broken when filename contains accent

### ISSUE THREAD

**Issue by jonasheinrich** [janko-m/shrine#93]
Hi Janko, 

I think the following happens: 

 - I choose a file with an accent in its filename (e.g. `été.pdf`)
 - shrine determines the filename from the path
 - shrine tries to upload the file and set the content disposition header including the filename
 - that breaks (probably the `POST` is invalid)

The error I get: `Aws::S3::Errors::SignatureDoesNotMatch: The request signature we calculated does not match the signature you provided. Check your key and signing method.`

Solution would be to url encode the filename. I think storing the filename decoded is fine so probably it is the best to encode everytime there's gonna be a request. 

What do you think?

Jonas

**Comment by janko-m** [comment]
Thanks for reporting. I've found the matching aws-sdk issue – https://github.com/aws/aws-sdk-ruby/issues/1230). I agree, I think a good solution would be to URI-encode the filename both on upload and when generating a presigned URL. I will push a fix shortly.

**Comment by janko-m** [comment]
Also, I would normally prefer to just wait for the bug to be fixed in the 3rd party library itself, but since the aws-sdk issue was first opened in July and hasn't been fixed since, it makes sense to make a workaround in Shrine.

**Comment by jonasheinrich** [comment]
Thanks again! 👍
